(function(){var e=PaymentsPortal2.modules.define;e("components/PurchaseFinancingOfferComponent","css-utils lang component components/SetPaymentPlanSelectComponent/validators jQuery AUI!P".split(" "),function(e,c,f,g,h,d){return f.extend({initialize:function(a,b){this.instrumentId=b.data.instrumentId;this.isDisplayable=b.data.isDisplayable;this.financialOfferDisplayStringsMap=b.data.financialOfferDisplayStringsMap;this.isMobile="mobile"===a.options.deviceType;this.isPurchaseFinancingPopoverShown=this.shouldShowPurchaseFinancingPopover=
!1;this.defaultPurchaseFinancingOffer=this.highlightedPurchaseFinancingOffer=this.selectedPurchaseFinancingOffer=b.data.maybeSelectedOfferId;g.push(c.bind(this._validator,this));this.eventRegistryCompleted=this.isCardSelected=!1},bindToElements:function(){this.getDOMElementsByPrefix("purchaseFinancingMobileTouchLink-").click(c.bind(this._handleTouchLinkClick,this))},bindToEvents:function(){this.widget.on("togglePurchaseFinancingOffers",this,function(a){this.isDisplayable&&this.instrumentId===a.instrumentId&&
(this._selectDefaultOffer(),this._togglePurchaseFinancingOffers(a.isSelected))})},bindToDesktopPopUpElements:function(){this.getDOMElement("purchaseFinancingAcceptButton-"+this.instrumentId).click(c.bind(this._handleOnClickAccept,this));this.getDOMElement("purchaseFinancingDeclineButton-"+this.instrumentId).click(c.bind(this._handleOnClickDecline,this))},bindToMobilePopUpElements:function(){var a=this;d.when("A","a-popover","ready").execute(function(b,k){a.getDOMElement("purchaseFinancingAcceptButton-"+
a.instrumentId).click(c.bind(a._handleOnClickAccept,a));a.getDOMElement("purchaseFinancingDeclineButton-"+a.instrumentId).click(c.bind(a._handleOnClickDecline,a));a.getDOMElementsByPrefix("purchaseFinancingOfferRadioButton-").click(function(b){a._purchaseFinancingOfferSelected(h(b.currentTarget))})})},_togglePurchaseFinancingOffers:function(a){this.isCardSelected=a;var b=this.getDOMElement(this.isMobile?"purchaseFinancingMobileTouchLink-"+this.instrumentId:"purchaseFinancingOffers");e.toggleElement(b,
a);this.widget.trigger("toggleFinancialOffer",{instrumentId:this.instrumentId,isSelected:!0,isAddressChallenged:!0})},_handleOnClickAccept:function(){if(this.isCardSelected){if(this.isMobile)this.selectedPurchaseFinancingOffer=this.highlightedPurchaseFinancingOffer,this.getDOMElement("selectedPurchaseFinancingOfferText-"+this.instrumentId).text(this.financialOfferDisplayStringsMap[this.selectedPurchaseFinancingOffer]),this.getDOMElement("hiddenFinancialOfferIdInput"+this.instrumentId).val(this.selectedPurchaseFinancingOffer),
this._updateSelectedOffer(this.selectedPurchaseFinancingOffer);else{this.shouldShowPurchaseFinancingPopover=!1;this.isPurchaseFinancingPopoverShown=!0;var a=this.getDOMElement("purchaseFinancingDropDownSelector-"+this.instrumentId)[0];this._updateSelectedOffer(a.options[a.selectedIndex].value);this.widget.trigger("ContinueButtonClicked")}this._closePopover()}},_handleOnClickDecline:function(){if(this.isCardSelected){if(this.isMobile)this.selectedPurchaseFinancingOffer=this.defaultPurchaseFinancingOffer,
this.getDOMElement("selectedPurchaseFinancingOfferText-"+this.instrumentId).text(this.financialOfferDisplayStringsMap[this.selectedPurchaseFinancingOffer]),this.getDOMElement("hiddenFinancialOfferIdInput"+this.instrumentId).val(this.selectedPurchaseFinancingOffer);else{var a=this.instrumentId,b=this.defaultPurchaseFinancingOffer;d.when("a-dropdown").execute(function(c){c.setValue("pmts-financial-offer-dropdown-native-id-"+a,b)});this.isPurchaseFinancingPopoverShown=this.shouldShowPurchaseFinancingPopover=
!1}this._updateSelectedOffer(this.defaultPurchaseFinancingOffer);this._closePopover()}},_validator:function(){if(!this.isCardSelected)return!0;var a=this.getDOMElement("purchaseFinancingDropDownSelector-"+this.instrumentId)[0];!this.isPurchaseFinancingPopoverShown&&a&&a.selectedIndex&&1<a.selectedIndex&&(this.getDOMElement("purchaseFinancingPopover-"+this.instrumentId).click(),this.eventRegistryCompleted||(this.bindToDesktopPopUpElements(),this.eventRegistryCompleted=!0),this.shouldShowPurchaseFinancingPopover=
!0);!this.isPurchaseFinancingPopoverShown&&a&&a.selectedIndex&&1===a.selectedIndex&&this._handleOnClickAccept();this.isMobile?this._updateSelectedOffer(this.selectedPurchaseFinancingOffer):a&&a.selectedIndex&&1<a.selectedIndex?this._updateSelectedOffer(a.options[a.selectedIndex].value):this._updateSelectedOffer(this.defaultPurchaseFinancingOffer);return!this.shouldShowPurchaseFinancingPopover},_purchaseFinancingOfferSelected:function(a){var b=a.data("financial-offer-id");b&&this.highlightedPurchaseFinancingOffer!==
b&&(this.getDOMElement("purchaseFinancingOfferRadioButton-"+this.highlightedPurchaseFinancingOffer).removeClass("pmts-selected"),a.addClass("pmts-selected"),a.find("input[type=radio]").prop("checked",!0),this.highlightedPurchaseFinancingOffer=b)},_updateSelectedOffer:function(a){this.isMobile?document.getElementsByName("ppw-"+this.instrumentId+"_financialOfferId").forEach(function(b){"hidden"===b.type&&(b.value=a)}):d.when("a-dropdown").execute(function(b){try{b.setValue("pmts-financial-offers-dropdown-native-id",
a)}catch(c){}})},_handleTouchLinkClick:function(){this.eventRegistryCompleted||(this.bindToMobilePopUpElements(),this.eventRegistryCompleted=!0);var a=this.getDOMElement("purchaseFinancingOfferRadioButton-"+this.selectedPurchaseFinancingOffer),b=a.find("input[type=radio]");a.addClass("pmts-selected");b.prop("checked",!0);this.selectedPurchaseFinancingOffer!==this.highlightedPurchaseFinancingOffer&&(a=this.getDOMElement("purchaseFinancingOfferRadioButton-"+this.highlightedPurchaseFinancingOffer),b=
a.find("input[type=radio]"),a.removeClass("pmts-selected"),b.prop("checked",!1),this.highlightedPurchaseFinancingOffer=this.selectedPurchaseFinancingOffer)},_selectDefaultOffer:function(){if(!this.isMobile){var a=this.instrumentId,b=this.defaultPurchaseFinancingOffer;d.when("a-dropdown").execute(function(c){c.setValue("pmts-financial-offer-dropdown-native-id-"+a,b)})}},_closePopover:function(){this.getDOMElement("close-purchaseFinancingAcceptButton-"+this.instrumentId).click()}})})})();
