(function(){var s=PaymentsPortal2.modules.define;s("components/CollectOVDIdComponent","css-utils lang component jQuery events/spinner-events clog".split(" "),function(e,s,W,h,t,c){var m,C,u,n,p,D,E,v,F,G,H,I,J,K,w,L,x,M,N,O,P,Q,R,S,T,y,r,U,k,d,z,q,l,A,V,f,B,g;return W.extend({initialize:function(a,b){g=this;v=b.data.JsBindingAddOVDIdSection;F=b.data.JsBindingAddOVDIdContent;G=b.data.JsBindingAddOVDIdInputSection;H=b.data.JsBindingAddOVDIdInputValue;I=b.data.JsBindingAddOVDIdButton;J=b.data.JsBindingAddOVDIdErrorSection;
K=b.data.JsBindingAddOVDIdErrorText;w=b.data.JsBindingAddOVDIdSuccessSection;L=b.data.JsBindingAddOVDIdSuccessHeading;x=b.data.Signature;M=b.data.Payload;N=b.data.MarketplaceId;O=b.data.CustomerId;P=b.data.RequestId;T=b.data.ClientId;R=b.data.TimeStamp;Q=b.data.ServiceUrl;S=b.data.SecretToValidate;r=b.data.MandatoryOVDWeblabTreatment;y=!1;U=this.widget.getLocalizedString("apx_mandatory_ovd_require_error_message");k=r?"MandatoryOVDIdCollection":"OVDIdCollection";m="AADHAAR";C="AADHAAR_MOBILE";u="AADHAAR_DESKTOP";
n="PAN";p="PASSPORT";D="ELECTORAL";E="DRIVING_LICENSE";f={AADHAAR_MOBILE:12,AADHAAR_DESKTOP:14,PAN:10,PASSPORT:8,ELECTORAL:20,DRIVING_LICENSE:20}},bindToEvents:function(){var a=this;a.widget.on("selectableCashOnDeliverySelected",this,function(){e.toggleElement(this.getDOMElement(v),!0);c.logCounterMetric({feature:k+"WidgetViewed",resource:"_Count"});c.publishMetrics();r&&!y?this.widget.trigger("OVDVerificationIncompleteEvent",U):this.widget.trigger("OVDVerificationIncompleteEvent",null)});a.widget.on("selectableCashOnDeliveryDeselected",
this,function(){e.toggleElement(this.getDOMElement(v),!1);this.widget.trigger("OVDVerificationIncompleteEvent",null)});a.widget.on("ovdIdSubmitted",this,function(b){c.logCounterMetric({feature:k+"AddOVDClick",resource:"_Count"});c.publishMetrics();a.widget.trigger(t.showSpinner);a._makeCORSRequest({url:Q,type:"POST",messageToVerify:M,signature:x,onsuccess:a._corsSuccessHandler,onerror:a._corsErrorHandler,data:{marketplaceId:N,customerId:O,documentId:a._getDocumentId(),documentType:a._getDocumentType(),
authType:"NONE",clientId:T,timestamp:parseFloat(R),secretToValidate:S,signedMessage:x,requestContext:{requestId:P}}})})},bindToElements:function(){var a=this;z=h(".ovdIdDropdown");d=this.getDOMElement(H);q=this.getDOMElement(J);l=this.getDOMElement(K);this.getDOMElement(w);A=this.getDOMElement(L);a.$addOVDButton=this.getDOMElement(I);B="mobile"===a.widget.options.deviceType;V={AADHAAR:a._validateAadhaar,PAN:a._validatePanCard,PASSPORT:a._validatePassport,DRIVING_LICENSE:a.validateDriverLicense,ELECTORAL:a.validateVoterIdCard};
!1===B&&(d.keydown(function(b){return a._restrictCharacters(b)}),d.keyup(function(b){return a._formatter(b)}));z.change(function(){a._hideErrors();e.showElement(a.getDOMElement(G));a._setInputMaxLength();c.logCounterMetric({feature:"OVDIdCollectionDropdownChange",resource:"_Count"});c.publishMetrics()});a.$addOVDButton.click(function(){a._hideErrors();a._validateOVD()&&a.widget.trigger("ovdIdSubmitted");return!1})},_parseAadhaar:function(a){return a.trim().split(" ").join("")},_validateAadhaar:function(a){return/^[1-9]\d{3}\s?\d{4}\s?\d{4}$/.test(a)&&
g._validateAadhaarVerhoffAlgorithm(a)},_validatePanCard:function(a){return/^[A-Z]{5}\d{4}[A-Z]$/.test(a)},_validatePassport:function(a){return/^[A-Z][0-9]\d\s?\d{4}[0-9]$/.test(a)},validateDriverLicense:function(a){return/^[A-Z0-9]{5,20}$/.test(a)},validateVoterIdCard:function(a){return/^[A-Z0-9]{5,15}$/.test(a)},_validateAadhaarVerhoffAlgorithm:function(a){var b=[[0,1,2,3,4,5,6,7,8,9],[1,2,3,4,0,6,7,8,9,5],[2,3,4,0,1,7,8,9,5,6],[3,4,0,1,2,8,9,5,6,7],[4,0,1,2,3,9,5,6,7,8],[5,9,8,7,6,0,4,3,2,1],[6,
5,9,8,7,1,0,4,3,2],[7,6,5,9,8,2,1,0,4,3],[8,7,6,5,9,3,2,1,0,4],[9,8,7,6,5,4,3,2,1,0]],X=[[0,1,2,3,4,5,6,7,8,9],[1,5,7,6,2,8,3,0,9,4],[5,8,0,3,7,9,6,1,4,2],[8,9,1,6,0,4,3,5,2,7],[9,4,5,3,1,2,6,8,7,0],[4,2,8,6,5,7,3,9,0,1],[2,7,9,3,8,0,6,4,1,5],[7,0,4,6,9,1,3,2,5,8]],c=0;a=a.split("").map(Number).reverse();for(var d=0;d<a.length;d++)c=b[c][X[d%8][a[d]]];return 0===c},_hideErrors:function(){e.toggleElement(q,!1);d.removeClass("a-form-error")},_validateOVD:function(){return V[this._getDocumentType()](g._getDocumentId())?
!0:(l.text(h("#"+this._getDocumentType()+"-error").text()),e.toggleElement(q,!0),d.addClass("a-form-error"),!1)},_getDocumentType:function(){return z.val()},_getDocumentId:function(){return d.val().trim().split("-").join("").toUpperCase()},_setInputMaxLength:function(){d.val("");var a=g._getDocumentType();a===m&&!0===B?d.attr("maxlength",f[C]):a===m?d.attr("maxlength",f[u]):a===n?d.attr("maxlength",f[n]):a===p?d.attr("maxlength",f[p]):d.attr("maxlength",f[E])},_restrictCharacters:function(a){var b=
this._getDocumentType(),d=this._getDocumentId(),c=!0,e=!0;a=this._getCharCode(a);if(8===a||37===a||39===a)return!0;b===m?(c=48<=a&&57>=a,e=d.length<f[u]):e=b===n?d.length<f[n]:b===p?d.length<f[p]:d.length<f[D];return c&&e},_getCharCode:function(a){return a.charCode?a.charCode:a.which},_formatter:function(a){if(this._getDocumentType()===m){var b=/\d{1,4}/g,c=this._getDocumentId();a=this._getCharCode(a);if(0===c.length||8===a)return!0;c=0===c.length%4&&12>c.length?c.match(b).join("-")+"-":c.match(b).join("-");
d.val(c)}return!0},_corsSuccessHandler:function(a){a=JSON.parse(a.responseText);g.widget.trigger(t.hideSpinner);c.logCounterMetric({feature:k,resource:"_Count"});"FAILURE"===a.status?(c.logCounterMetric({feature:k,resource:"_FailureCount"}),c.logCounterMetric({feature:k,resource:"_"+a.errorType}),"DUPLICATE_DOCUMENT_ID"===a.errorType?l.text(h("#"+g._getDocumentType()+"-dup-error").text()):"REQUEST_TIME_ELAPSED_ERROR"===a.errorType?l.text(h("#apx-ovd-widget-expired").text()):l.text(h("#apx-ovd-generic-error").text()),
e.toggleElement(q,!0)):(c.logCounterMetric({feature:k,resource:"_SuccessCount"}),e.hideElement(g.getDOMElement(F)),e.showElement(g.getDOMElement(w)),A.text(h(".ovdIdDropdown option:selected").text().trim()+A.text()),r&&(y=!0,g.widget.trigger("MandatoryOVDCollectionSuccessful")));c.publishMetrics()},_corsErrorHandler:function(a){g.widget.trigger(t.hideSpinner);c.logCounterMetric({feature:k,resource:"_ErrorCount"});c.publishMetrics();l.text(h(".apx-ovd-generic-error").text());e.toggleElement(q,!0)},
_extendParameters:function(a){h.extend(a,{data:JSON.stringify(a.data),crossDomain:!0,dataType:"json",contentType:"application/json",headers:{"Content-Encoding":"amz-1.0","X-Amz-Target":a.operation,"Content-Type":"application/json",signature:a.signature}})},_createCORSRequest:function(a){var b=new XMLHttpRequest;"withCredentials"in b?(b.operation=a.operation,b.open(a.type,a.url,!0)):"undefined"!==typeof XDomainRequest?(b=new XDomainRequest,b.operation=a.operation,b.open(a.type,a.url,!0)):b=null;b&&
h.each(a.headers,function(a,c){b.setRequestHeader(a,c)});return b},_makeCORSRequest:function(a){this._extendParameters(a);var b=this._createCORSRequest(a);if(!b)return null;b.onload=function(){a.onsuccess(b)};b.onerror=function(b){a.onerror(b)};b.send(a.data);return b}})});s("components/DefaultComponent",["component"],function(e){return e.extend({initialize:function(){window.alert("DefaultComponent initialize!")}})})})();
