(function(){var f=PaymentsPortal2.modules.define;f("components/SelectableZipPayListComponent",["form-component"],function(d){return d});f("components/ZipPayListItemComponent","components/SelectableDPMInstrumentListItemComponent events/InstrumentRowSelectedEvent lang jQuery css-utils component".split(" "),function(d,f,g,e,h,l){return d.extend({initialize:function(a,b){this._maybeDisableInstrumentRow()},_maybeDisableInstrumentRow:function(){var a=this._getContainerElement();0<a.find(".pmts-zip-no-balance-text").length&&
(a.find("img").each(function(a,c){e(c).css("opacity","0.5")}),a.find(".pmts-zip-balance-instrument-type").each(function(a,c){e(c).addClass("a-color-tertiary")}),a.find("input[type=radio]").each(function(a,c){e(c).prop("disabled",!0)}))},_getContainerElement:function(){return this.getDOMElement("POAInstrumentContainer-"+this._getInstrumentId())},_triggerIsLineItemIneligibleEvent:function(){this._instrumentZipEnableGreyOut();this._instrumentZipUnclickable()},_instrumentZipEnableGreyOut:function(){this._getContainerElement().addClass("pmts-disabled-section")},
_instrumentZipUnclickable:function(){this._getContainerElement().addClass("pmts-pm-disabled")},_instrumentZipDisableGreyOut:function(){this._getContainerElement().removeClass("pmts-disabled-section")},_instrumentZipClickable:function(){this._getContainerElement().removeClass("pmts-pm-disabled")},_hidePopOverMsgWhenGCUnselected:function(){this.getDOMElement("pmts-show-msg-when-gc-selected").addClass("apx-js-hide")},_showPopOverMsgWhenGCSelected:function(){this.getDOMElement("pmts-show-msg-when-gc-selected").removeClass("apx-js-hide")},
_setZipPaymentInvalid:function(a){a=[this.widget.getLocalizedString(a)];this._triggerBackingInstrumentSelectedEvent(a)},bindToElements:function(){var a=this;0===a._getContainerElement().find(".pmts-zip-no-balance-text").length&&a.getDOMElementsByPrefix("POAInstrumentContainer").click(function(b){e(b.currentTarget).data("disabled")||a.poaInstrumentClicked(a._instrumentId)});a.getDOMElement("ZipBalanceRefresh").find(".pmts-zip-balance-refresh-link").click(function(){a.widget.trigger("ZipBalanceRefresh")})},
bindToEvents:function(){var a=this;a.widget.on("initializeRecommendedInstrument",a,function(b){a.data.isLineItemIneligible?(a._triggerIsLineItemIneligibleEvent(),b.instrumentId===a._getInstrumentId()&&a._setZipPaymentInvalid("pmts_portal_payselect_empty_instrument_selection")):b.instrumentId===a._getInstrumentId()?(a.widget.trigger(f,{instrumentId:a._getInstrumentId()}),a.data.isMultiTenderEnabledWithZip||a.widget.trigger("deselectGiftCardCheckbox",{paymentMethod:a.data.paymentMethod})):a._onInstrumentDeselected()});
a.widget.on(f,a,function(b){a._instrumentRowSelected(b.instrumentId);g.isDefined(a.data.instrumentId)&&-1!==b.instrumentId.indexOf("amzn1.pm.pma.zip")&&a.data.isInsufficientCoverage&&a._setZipPaymentInvalid("pmts_portal_zp_error_insufficient_popover")});a.widget.on("optionalInstrumentSelected",a,function(b){"GC"!==b.paymentMethod||a.data.isMultiTenderEnabledWithZip||(a._instrumentZipEnableGreyOut(),a._instrumentZipUnclickable(),a._showPopOverMsgWhenGCSelected())});a.widget.on("optionalInstrumentDeselected",
a,function(b){"GC"!==b.paymentMethod||a.data.isLineItemIneligible||a.data.isMultiTenderEnabledWithZip||(a._instrumentZipDisableGreyOut(),a._instrumentZipClickable(),a._hidePopOverMsgWhenGCUnselected())});a.widget.on("ZipBalanceRefresh",a,function(b){a.widget.submitFormAJAX({"ppw-widgetState":a.widget.options.serializedState,"ppw-widgetEvent":"ZipBalanceRefreshEvent"})})}})});f("components/AddZipPayComponent","css-utils jQuery form-component lang AUI!P aui-helper".split(" "),function(d,f,g,e,h,l){return g.extend({_authenticationSourceId:"",
_authenticationSourceStatus:"",_AUCountryCodePrefix:"+61",_resendCodeClickCount:0,_emptyMobileNumberErrorMsg:{field:"zip_mobile_number",messageStringId:"pmts_portal_zp_error_no_mobile_number"},_invalidMobileNumberErrorMsg:{field:"zip_mobile_number",messageStringId:"pmts_portal_zp_error_invalid_mobile_number"},_emptyOTPErrorMsg:{field:"zip_one_time_password",messageStringId:"pmts_portal_zp_error_no_verification_code"},_invalidOTPErrorMsg:{field:"zip_one_time_password",messageStringId:"pmts_portal_zp_error_invalid_verification_code"},
_failedInternalCallErrorMsg:{messageStringId:"pmts_portal_zp_error_internal_fail"},initialize:function(a,b){this._isDesktop="desktop"===a.options.deviceType},bindToElements:function(){this.bindFormSubmissionHandler("getVerificationCodeButton","mobileNumber",this.handleSendOTPRequest);this.bindFormSubmissionHandler("resendCodeRequest","mobileNumber",this.handleResendOTPRequest);this.bindFormSubmissionHandler("verifyButton","verificationCode",this.handleVerifyOTPRequest)},loadModal:function(){"mobile"===
this.deviceType&&this.getDOMElement("bottomSheetTrigger").click()},handleSendOTPRequest:function(){var a=this,b=a._validateFormField("zip_mobile_number"),c=a.getDOMElement("zip_mobile_number").val(),b=a._validateMobileNumberInput(c,b),c=a._AUCountryCodePrefix+c;0===b.length?(a._handleValidRequest("getVerificationCodeButton","a-button-disabled","errorMessagesInlineContainer-zip_mobile_number"),a.widget.continueRequest({"ppw-widgetEvent":"ZipPaySendOTPEvent",zip_mobile_number:c,"ppw-widgetState":a.widget.options.serializedState},
{complete:function(){a.getDOMElement("getVerificationCodeButton").removeClass("a-button-disabled")},success:e.bind(function(b){a._checkMobileNumberRegistrationStatus(b.additionalWidgetResponseData.additionalData)},this),error:e.bind(function(){},this),queryParameters:a.widget._whitelistedQueryParameters("?sif_profile=ZIP_SIF_Profile")})):(d.hideElement(this.getDOMElement("errorMessagesInlineContainer")),a._renderErrorMessages(a.form._getLocalizedErrorMessages(b)));return!1},handleResendOTPRequest:function(){var a=
this,b=a._validateFormField("zip_mobile_number"),c=a.getDOMElement("zip_mobile_number").val(),b=a._validateMobileNumberInput(c,b);0===b.length&&a._validateResendOtpFrequencyCheck();c=a._AUCountryCodePrefix+c;0===b.length?(a._handleValidRequest(null,null,"errorMessagesInlineContainer-zip_mobile_number"),a.widget.continueRequest({"ppw-widgetEvent":"ZipPayResendOTPEvent",zip_mobile_number:c,"ppw-authenticationSourceId":a._authenticationSourceId,"ppw-widgetState":a.widget.options.serializedState},{success:e.bind(function(b){b=
b.additionalWidgetResponseData.additionalData;a._authenticationSourceStatus=b.authenticationSourceStatus;a._checkMobileNumberRegistrationStatus(b)},this),error:e.bind(function(){},this),queryParameters:a.widget._whitelistedQueryParameters("?sif_profile=ZIP_SIF_Profile")})):(d.hideElement(this.getDOMElement("errorMessagesInlineContainer")),a._renderErrorMessages(a.form._getLocalizedErrorMessages(b)));return!1},handleVerifyOTPRequest:function(){var a=this,b=a._validateFormField("zip_one_time_password"),
c=a.getDOMElement("zip_one_time_password").val(),b=a._validateOTPInput(c,b);0===b.length?(a._handleValidRequest("verifyButton","a-button-disabled","errorMessagesInlineContainer-zip_one_time_password"),a.widget.trigger("submitFormAjaxStarted"),a.widget.continueRequest({"ppw-widgetEvent":"ZipPayVerifyOTPEvent",zip_one_time_password:c,"ppw-authenticationSourceId":a._authenticationSourceId,"ppw-widgetState":a.widget.options.serializedState},{complete:function(){a.getDOMElement("verifyButton").removeClass("a-button-disabled");
a.widget.trigger("submitFormAjaxCompleted")},success:e.bind(function(b){var c=b.additionalWidgetResponseData.additionalData;"APPROVED"===c.authenticationSourceStatus?(a.widget._onAJAXContinueSuccess(b),a.closeAddZipPayPopover()):c.errors?(b=JSON.parse(c.errors),a.form.renderErrorMessages(b)):(b=[],b.push(a._failedInternalCallErrorMsg),a.form.renderErrorMessages(a.form._getLocalizedErrorMessages(b)))},this),error:e.bind(function(){},this),queryParameters:a.widget._whitelistedQueryParameters("?sif_profile=ZIP_SIF_Profile")})):
(d.hideElement(this.getDOMElement("errorMessagesInlineContainer")),a._renderErrorMessages(a.form._getLocalizedErrorMessages(b)));return!1},verificationCodeFormDisplay:function(a){d.toggleElement(this.getDOMElement("verificationCodeForm"),a)},hideGetVerificationCodeButtonAndShowResendCodeRequest:function(){d.hideElement(this.getDOMElement("getVerificationCodeButton"));d.showElement(this.getDOMElement("resendCodeRequest"))},closeAddZipPayPopover:function(){h.when("a-modal").execute(function(a){a&&(a=
a.get("addZipPayPopover"))&&a.hide()})},_handleValidRequest:function(a,b,c){this.form.resetErrors();null!=a&&null!=b&&this.getDOMElement(a).addClass(b);d.hideElement(this.getDOMElement(c))},_validateFormField:function(a){return e.filter(this.form.validateForm(),function(b){return b.field===a})},_validateMobileNumberInput:function(a,b){0!==a.length?/^\d+$/.test(a)?(9>a.length||9===a.length&&"4"!==a.charAt(0)||10===a.length&&"04"!==a.substring(0,2))&&b.push(this._invalidMobileNumberErrorMsg):b.push(this._invalidMobileNumberErrorMsg):
b.push(this._emptyMobileNumberErrorMsg);return b},_validateOTPInput:function(a,b){0!==a.length?/^\d+$/.test(a)?6!==a.length&&b.push(this._invalidOTPErrorMsg):b.push(this._invalidOTPErrorMsg):b.push(this._emptyOTPErrorMsg);return b},_validateResendOtpFrequencyCheck:function(){var a=this;a._resendCodeClickCount++;3>a._resendCodeClickCount?(a.getDOMElement("resendCodeRequest").addClass("apx-zipPay-link-disabled"),window.setTimeout(function(){a.getDOMElement("resendCodeRequest").removeClass("apx-zipPay-link-disabled")},
3E4)):a.getDOMElement("resendCodeRequest").addClass("apx-zipPay-link-disabled")},_checkMobileNumberRegistrationStatus:function(a){this._authenticationSourceId=a.authenticationSourceId;this._authenticationSourceStatus=a.authenticationSourceStatus;"PENDING"===this._authenticationSourceStatus?(this.form.clearValidationErrors(),this.hideGetVerificationCodeButtonAndShowResendCodeRequest(),this.verificationCodeFormDisplay(!0),d.hideElement(this.getDOMElement("errorMessagesInlineContainer")),d.hideElement(this.getDOMElement("errorMessagesInlineContainer-verificationCode"))):
(a.errors?a=JSON.parse(a.errors):(a=[],a.push(this._failedInternalCallErrorMsg)),this.form.renderErrorMessages(a))},_renderErrorMessages:function(a){var b=this,c=[],d=[],f=[],k={};e.forEach(a,function(a){a.field&&(k[a.field]||(k[a.field]=[]),k[a.field].push(a),b.form.blameFormField(a.field,!0));a.validation&&a.fieldMetricValueType&&a.fieldValue&&(c.push(a.validation),d.push(a.fieldMetricValueType),f.push(a.fieldValue))});if(b._isDesktop){var g=b.form._getFormAlertsContainer();void 0!==g.domElement&&
l.getFormAlertsContainerHelper(g.messageDisplayType,g.domElement).render(a)}else{var h=b.form._getFormFieldAlertContainers();e.forEach(e.keys(h),function(a){l.getFormAlertsContainerHelper("inline",h[a]).render(k[a])})}}})})})();
