(function(){var h=PaymentsPortal2.modules.define;h("components/AmazonPayEMIComponent","component jQuery lang css-utils events/InstrumentRowSelectedEvent public-event-registry continuable AUI!P".split(" "),function(h,k,n,e,f,p,q,m){return h.extend(q,{isAPBWithEMIEnabled:!1,installmentOfferBOsWithoutAPB:[],installmentOfferBOsWithAPB:[],isPaylastEligible:!1,isPayLaterSelectedByDefault:!1,initialize:function(a,b){this.currentInstrumentId=b.data.instrumentId;this.isAmazonPayEMIDisplayable=b.data.isDisplayable;
this.isAPBWithEMIEnabled=b.data.isAPBWithEMIEnabled;this.isAmazonPayEMIDisplayable&&p.register(f);this.installmentOfferBOsWithoutAPB=b.data.installmentOfferBOsWithoutAPB;this.installmentOfferBOsWithAPB=b.data.installmentOfferBOsWithAPB;this.isAPBWithEMIEnabled&&0!==this.installmentOfferBOsWithoutAPB.length&&this.hideEMIRecomendationMessage();this.isPaylastEligible=b.data.isPaylastEligible;this.isPayLaterSelectedByDefault=b.data.isPayLaterSelectedByDefault;this.isImportantEmiInfoEnabled=b.data.isImportantEmiInfoEnabled},
_isAmazonPayBalanceSelected:function(){return this.widget.get("apbCheckboxSelected")},_isAmazonPayEmiAvailable:function(){return(!this._isAmazonPayBalanceSelected()||this.isAPBWithEMIEnabled)&&this.isAmazonPayEMIDisplayable},_getAmazonPayEMIContainer:function(){return this.getDOMElementsByPrefix("amazonPayEMIContainer")},_getInstrumentSelectionInputElement:function(){return this.getDOMElement("instrumentRowSelection-"+this.currentInstrumentId)},_onInstrumentSelected:function(){this._getAmazonPayEMIContainer().addClass("pmts-selected");
this._getInstrumentSelectionInputElement().prop("checked",!0)},_onInstrumentDeselected:function(){this._getAmazonPayEMIContainer().removeClass("pmts-selected")},_amazonPayEMIOptionClicked:function(a){this._isAmazonPayBalanceSelected()&&!this.isAPBWithEMIEnabled||this.widget.trigger(f,{instrumentId:this.currentInstrumentId})},_showAmazonPayEMIDisabledWrapper:function(){e.showElement(this.getDOMElement("amazonCreditUnavailableMessage"))},_showAmazonPayEMIDropdownWrapper:function(a){e.showElement(this.getDOMElement("amazonPayEMIDropdown"))},
_hideAmazonPayEMIDisabledWrapper:function(){e.hideElement(this.getDOMElement("amazonCreditUnavailableMessage"))},_hideAmazonPayEMIDropdownWrapper:function(a){e.hideElement(this.getDOMElement("amazonPayEMIDropdown"))},_showAmazonPayEMINoCostEMIAvailableWrapper:function(){e.showElement(this.getDOMElement("noCostEMIStringRow"))},_hideAmazonPayEMINoCostEMIAvailableWrapper:function(){e.hideElement(this.getDOMElement("noCostEMIStringRow"))},_getAmazonPayEMIInstallmentHiddenInput:function(a){return this.getDOMElement("amazonPayEMISelectionHiddenInput-"+
a).add(this.getDOMElement("amazonPayEMISelectionHiddenInput-"))},_getPrimaryViewButtonDisplay:function(a){return this.getDOMElement("amazonPayEMIOfferButtonText-"+a).add(this.getDOMElement("amazonPayEMIOfferButtonText-"))},_getAmazonPayEMIInstallmentTouchLink:function(a){return this.getDOMElement("amazonPayEMIMobileTouchLink-"+a).add(this.getDOMElement("amazonPayEMIMobileTouchLink-"))},_triggerBackingInstrumentSelectedEvent:function(a,b){this.widget.trigger("backingInstrumentSelected",{instrumentId:a,
errors:b})},closeAmazonPayEMIInstallmentsSecondaryPopover:function(a){m.when("a-secondary-view").execute(function(b){b&&(b=b.get("amazonPayEMISecondaryPopover-"+a))&&b.hide()});this._triggerBackingInstrumentSelectedEvent(this.currentInstrumentId,null)},_updateInstallmentOptionsAccordionStateToLastSelectedInstallment:function(a){a=this.currentInstrumentId;var b=this._getAmazonPayEMIInstallmentHiddenInput(a)[0].value;k("[data-a-accordion-name='installmentOptionsAccordion-"+a+"'] [data-a-accordion-row-name='"+
("installmentOptionAccordionRow-"+a+b)+"'] a").click()},_chooseInstallmentButtonClick:function(a,b,c){var d=this.currentInstrumentId;a=k(a.currentTarget);var l=a.find("input"),e=a.find(".a-section").html(),f=this;if(d===l.data("instrumentid").toString())if(d=null,this.isImportantEmiInfoEnabled&&(d=this.createImportantEmiInformationMessages(l)),d&&0<d.length){a=this.widget.getLocalizedString("apx_important_emi_info_header_message");var h=k('<ul class="a-unordered-list a-vertical"/>');d.forEach(function(a){k("<li/>").html('<span class="a-list-item">'+
a+"</span>").appendTo(h)});var d={name:"emiImportantInfoModal-AmazonPayEMI",inlineContent:h[0].outerHTML,header:a,footer:'<span class="a-button-primary a-spacing-none a-button a-button-small a-width-medium"><span class="a-button-inner"><input type="submit" class="a-button-input a-button-text"/><span class="a-button-text">OK</span></span></span>'},g=c.get(d.name);a=!1;null==g?(b=b.$("<div/>"),g=c.create(b,d),a=!0):g.update(d);g.show();a&&(g.$container.find(".a-popover-footer").addClass("a-padding-small"),
g.$container.find("input").bind("click",function(a){c.remove(g);f._displaySelectedInstallmentPlan(l,e)}))}else this._displaySelectedInstallmentPlan(l,e)},createImportantEmiInformationMessages:function(a){var b=this.getEligibleInstallmentOfferBOs(),c=a.data("financialofferid"),b=this.getSelectedInstallmentOfferBO(b,c);if(c=b.maybeTotalPrincipalAmount){var c=Math.round(c.value),d=a.data("paymentmethodcode");a=a.data("installmentstartdate");if(1<b.numberOfInstallments&&"AmazonCredit"===d)return this.prepareAmazonEMIStrings(c,
a)}return null},getSelectedInstallmentOfferBO:function(a,b){var c=null;a&&(c=a.filter(function(a){return a.financialOfferId===b})[0]);return c},prepareAmazonEMIStrings:function(a,b){var c=this.widget.getLocalizedString("apx_important_emi_info_aemi_limit_utilization",{principal:a});if(b&&""!==b){var d=this.widget.getLocalizedString("apx_important_emi_info_aemi_due_date",{installmentStartDate:b});return[c,d]}return[c]},getEligibleInstallmentOfferBOs:function(){return this._isAmazonPayBalanceSelected()?
this.installmentOfferBOsWithAPB:this.installmentOfferBOsWithoutAPB},_displaySelectedInstallmentPlan:function(a,b){var c=this.currentInstrumentId;c===a.data("instrumentid").toString()&&(this._getAmazonPayEMIInstallmentHiddenInput(c).val(a.data("financialofferid")),this._getPrimaryViewButtonDisplay(c).html(b),this.isPaylastEligible&&(""!==a.data("financialofferid")?this.triggerEventToUpdateOrderTotalForNCEDiscount(a.data().financialofferid):this.widget.trigger("UpdateOrderTotalForNoCostEMIDiscount",
{noCostEMIValue:0,instrumentId:this.currentInstrumentId})),this.isAPBWithEMIEnabled&&this.widget.trigger("installmentPlanChanged",{instrumentId:c,displayHtml:b,installmentPlanId:a.data("financialofferid")}),c=c.split(".").join("-"),this.installmentSelected=!0,this._hideAmazonPayEMINoCostEMIAvailableWrapper(),this.closeAmazonPayEMIInstallmentsSecondaryPopover(c))},_isInstrumentSelected:function(){return this._getAmazonPayEMIContainer().hasClass("pmts-selected")},_getAmazonPayEMIHeading:function(){return this.getDOMElement("amazonPayEMIHeading")},
_toggleAmazonPayEMIOption:function(a){this._isAmazonPayBalanceSelected()&&!this.isAPBWithEMIEnabled&&this._disableAmazonPayEMIOption();if(!this._isAmazonPayBalanceSelected()||this.isAPBWithEMIEnabled)this._hideAmazonPayEMIDisabledWrapper(),this._showAmazonPayEMINoCostEMIAvailableWrapper(),this._getAmazonPayEMIHeading().removeClass("pmts-disabled-section"),this._getInstrumentSelectionInputElement().prop("disabled",!1);this._isInstrumentSelected()&&!this._isAmazonPayEmiAvailable()&&(this._onInstrumentDeselected(),
this._getInstrumentSelectionInputElement().prop("checked",!1),this.widget.trigger(f,{}),this.setContinuable(!1),this.widget.trigger("PaymentPlanSelected",{isValid:!1}));this.isAPBWithEMIEnabled&&(this._isAmazonPayBalanceSelected()&&0===this.installmentOfferBOsWithAPB.length?this._disableAmazonPayEMIOption():this._isAmazonPayBalanceSelected()||0!==this.installmentOfferBOsWithoutAPB.length||this._disableAmazonPayEMIOption())},_disableAmazonPayEMIOption:function(){this._showAmazonPayEMIDisabledWrapper();
this._hideAmazonPayEMIDropdownWrapper();this._hideAmazonPayEMINoCostEMIAvailableWrapper();this._getAmazonPayEMIHeading().addClass("pmts-disabled-section");this._getInstrumentSelectionInputElement().prop("disabled",!0)},_enableAmazonPayEMIOption:function(){this._onInstrumentSelected();this._showAmazonPayEMIDropdownWrapper();this._showAmazonPayEMINoCostEMIAvailableWrapper();this._hideAmazonPayEMIDisabledWrapper();this.isPayLaterSelectedByDefault&&(this.installmentSelected=!0);this.installmentSelected&&
(this._triggerBackingInstrumentSelectedEvent(this.currentInstrumentId,null),this._hideAmazonPayEMINoCostEMIAvailableWrapper())},displayEMIRecomendationMessage:function(a){var b=this.getDOMElement("emiRecomendationMessage");e.toggleElement(b,!0);b[0].getElementsByClassName("a-alert-content")[0].textContent=a},hideEMIRecomendationMessage:function(){var a=this.getDOMElement("emiRecomendationMessage");e.toggleElement(a,!1)},triggerEventToUpdateOrderTotalForNCEDiscount:function(a){var b=this.getEligibleInstallmentOfferBOs();
if(a=this.getSelectedInstallmentOfferBO(b,a))(a=a.maybeOfferDiscountAmount)&&0<a.value?this.widget.trigger("UpdateOrderTotalForNoCostEMIDiscount",{noCostEMIValue:Math.round(a.value)}):this.widget.trigger("UpdateOrderTotalForNoCostEMIDiscount",{noCostEMIValue:0})},bindToEvents:function(){var a=this;this.getDOMElementsByPrefix("amazonPayEMIContainer").click(n.bind(this._amazonPayEMIOptionClicked,this));a.widget.on(f,this,function(a){if(a.instrumentId!==this.currentInstrumentId||this._isAmazonPayBalanceSelected()&&
!this.isAPBWithEMIEnabled){if(this._onInstrumentDeselected(),this._hideAmazonPayEMIDropdownWrapper(),!this._isAmazonPayBalanceSelected()||this.isAPBWithEMIEnabled)this._showAmazonPayEMINoCostEMIAvailableWrapper(),this.isAPBWithEMIEnabled&&this._isAmazonPayBalanceSelected()&&0===this.installmentOfferBOsWithAPB.length?this._hideAmazonPayEMINoCostEMIAvailableWrapper():this.isAPBWithEMIEnabled&&!this._isAmazonPayBalanceSelected()&&0===this.installmentOfferBOsWithoutAPB.length&&this._hideAmazonPayEMINoCostEMIAvailableWrapper()}else this.isAPBWithEMIEnabled?
(this._isAmazonPayBalanceSelected()&&0<this.installmentOfferBOsWithAPB.length&&this._enableAmazonPayEMIOption(),!this._isAmazonPayBalanceSelected()&&0<this.installmentOfferBOsWithoutAPB.length&&this._enableAmazonPayEMIOption()):this._enableAmazonPayEMIOption()});if(this.isPaylastEligible)a.widget.on("GetNoCostEMISelectionDiscountValue",a,function(b){b.instrumentId===a.currentInstrumentId&&(b=this._getCreditCardInstallmentMobileHiddenInput(b.instrumentId))&&0<b.length&&this.triggerEventToUpdateOrderTotalForNCEDiscount(b[0].value)});
a.widget.on("apbSelectionChanged",a,function(b){if(this.isAPBWithEMIEnabled){var c="";this._isAmazonPayBalanceSelected()&&0===this.installmentOfferBOsWithAPB.length?(c=a.widget.getLocalizedString("apx_payselect_apb_plus_emi_feature_deselect_apb_to_view_emi_options_message"),this.displayEMIRecomendationMessage(c)):this._isAmazonPayBalanceSelected()||0!==this.installmentOfferBOsWithoutAPB.length?this.hideEMIRecomendationMessage():(c=a.widget.getLocalizedString("apx_payselect_apb_plus_emi_feature_select_apb_to_view_emi_options_message"),
this.displayEMIRecomendationMessage(c))}this.isAmazonPayEMIDisplayable&&(this.isAPBWithEMIEnabled&&this._isInstrumentSelected()?(this._onInstrumentDeselected(),this._getInstrumentSelectionInputElement().prop("checked",!1),this.widget.trigger(f,{}),this.setContinuable(!1),this.widget.trigger("PaymentPlanSelected",{isValid:!1}),b="",b=this._isAmazonPayBalanceSelected()&&0===this.installmentOfferBOsWithAPB.length?a.widget.getLocalizedString("apx_payselect_apb_plus_emi_feature_deselect_apb_to_view_emi_options_message"):
this._isAmazonPayBalanceSelected()||0!==this.installmentOfferBOsWithoutAPB.length?a.widget.getLocalizedString("apx_payselect_apb_plus_emi_feature_emi_plan_change_message"):a.widget.getLocalizedString("apx_payselect_apb_plus_emi_feature_select_apb_to_view_emi_options_message"),this.widget.trigger("ChangeInAPBSelectionAfterInstallmentPlanSelectionEvent",{message:b})):this._toggleAmazonPayEMIOption(b))});a.widget.on("updatePrimaryButtonDisplayString",this,function(a){if(this.currentInstrumentId===a.instrumentId){var c=
this._getPrimaryViewButtonDisplay(this.currentInstrumentId),d=this._getAmazonPayEMIInstallmentHiddenInput(a.instrumentId);""===a.displayString&&(a.displayString=this.widget.getLocalizedString("apx_amazon_pay_emi_sec_view_default_text"));c.html(a.displayString);d.val(a.installmentPlanId)}});m.when("A","a-modal","a-secondary-view").execute(function(b,c,d){b.on("a:popover:afterHide:amazonPayEMISecondaryPopover-"+this.currentInstrumentId,function(a){this._updateInstallmentOptionsAccordionStateToLastSelectedInstallment(a)});
b.declarative("chooseInstallmentButton","click",function(d){a._chooseInstallmentButtonClick(d.$event,b,c)});b.on("a:popover:dismiss:emiImportantInfoModal-AmazonPayEMI",function(b){b="amazonPayEMISecondaryPopover-"+a.currentInstrumentId.replace(/\./g,"-");(b=d.get(b))&&b.show()})})}})})})();
