export const GET_STUDENT_DATA = "GET_STUDENT_DATA";
export const CHANGE_NAME = "CHANGE_NAME";
export const CHANGE_PROFILE_PIC = "CHANGE_PROFILE_PIC";
export const CHANGE_OBJECTIVE = "CHANGE_OBJECTIVE";
export const CHANGE_CONTACT_INFORMATION = "CHANGE_CONTACT_INFORMATION";
export const CHANGE_EDUCATION = "CHANGE_EDUCATION";
export const CHANGE_EXPERIENCE = "CHANGE_EXPERIENCE";
export const CHANGE_SKILLS = "CHANGE_SKILLS";
export const UPDATE_FILTERED_JOBS = "UPDATE_FILTERED_JOBS";
export const JOB_SEARCH_PAGINATION = "JOB_SEARCH_PAGINATION";
export const JOB_SEARCH_SORT = "JOB_SEARCH_SORT";
export const DELETE_EXPERIENCE= "DELETE_EXPERIENCE";
export const DELETE_EDUCATION ="DELETE_EDUCATION";
export const ADD_EXPERIENCE= "ADD_EXPERIENCE";
export const ADD_EDUCATION ="ADD_EDUCATION";










