(function(g){var h=window.AmazonUIPageJS||window.P,k=h._namespace||h.attributeErrors,f=k?k("JQueryUI_Core_AUIBuild",""):h;f.guardFatal?f.guardFatal(g)(f,window):f.execute(function(){g(f,window)})})(function(g,h,k){g.when("jQuery").register("jQueryUI-core",function(f){(function(b,f){function g(a,c){var d,e;d=a.nodeName.toLowerCase();if("area"===d){d=a.parentNode;e=d.name;if(!a.href||!e||"map"!==d.nodeName.toLowerCase())return!1;d=b("img[usemap\x3d#"+e+"]")[0];return!!d&&h(d)}return(/input|select|textarea|button|object/.test(d)?
!a.disabled:"a"===d?a.href||c:c)&&h(a)}function h(a){return b.expr.filters.visible(a)&&!b(a).parents().addBack().filter(function(){return"hidden"===b.css(this,"visibility")}).length}var k=0,l=/^ui-id-\d+$/;b.ui=b.ui||{};b.extend(b.ui,{version:"1.10.3",keyCode:{BACKSPACE:8,COMMA:188,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,LEFT:37,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SPACE:32,
TAB:9,UP:38}});b.fn.extend({focus:function(a){return function(c,d){return"number"===typeof c?this.each(function(){var a=this;setTimeout(function(){b(a).focus();d&&d.call(a)},c)}):a.apply(this,arguments)}}(b.fn.focus),scrollParent:function(){var a;a=b.ui.ie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(b.css(this,"position"))&&/(auto|scroll)/.test(b.css(this,"overflow")+b.css(this,"overflow-y")+
b.css(this,"overflow-x"))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(b.css(this,"overflow")+b.css(this,"overflow-y")+b.css(this,"overflow-x"))}).eq(0);return/fixed/.test(this.css("position"))||!a.length?b(document):a},zIndex:function(a){if(a!==f)return this.css("zIndex",a);if(this.length){a=b(this[0]);for(var c;a.length&&a[0]!==document;){c=a.css("position");if("absolute"===c||"relative"===c||"fixed"===c)if(c=parseInt(a.css("zIndex"),10),!isNaN(c)&&0!==c)return c;a=a.parent()}}return 0},
uniqueId:function(){return this.each(function(){this.id||(this.id="ui-id-"+ ++k)})},removeUniqueId:function(){return this.each(function(){l.test(this.id)&&b(this).removeAttr("id")})}});b.extend(b.expr[":"],{data:b.expr.createPseudo?b.expr.createPseudo(function(a){return function(c){return!!b.data(c,a)}}):function(a,c,d){return!!b.data(a,d[3])},focusable:function(a){return g(a,!isNaN(b.attr(a,"tabindex")))},tabbable:function(a){var c=b.attr(a,"tabindex"),d=isNaN(c);return(d||0<=c)&&g(a,!d)}});b("\x3ca\x3e").outerWidth(1).jquery||
b.each(["Width","Height"],function(a,c){function d(a,c,d,f){b.each(e,function(){c-=parseFloat(b.css(a,"padding"+this))||0;d&&(c-=parseFloat(b.css(a,"border"+this+"Width"))||0);f&&(c-=parseFloat(b.css(a,"margin"+this))||0)});return c}var e="Width"===c?["Left","Right"]:["Top","Bottom"],g=c.toLowerCase(),h={innerWidth:b.fn.innerWidth,innerHeight:b.fn.innerHeight,outerWidth:b.fn.outerWidth,outerHeight:b.fn.outerHeight};b.fn["inner"+c]=function(a){return a===f?h["inner"+c].call(this):this.each(function(){b(this).css(g,
d(this,a)+"px")})};b.fn["outer"+c]=function(a,e){return"number"!==typeof a?h["outer"+c].call(this,a):this.each(function(){b(this).css(g,d(this,a,!0,e)+"px")})}});b.fn.addBack||(b.fn.addBack=function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))});b("\x3ca\x3e").data("a-b","a").removeData("a-b").data("a-b")&&(b.fn.removeData=function(a){return function(c){return arguments.length?a.call(this,b.camelCase(c)):a.call(this)}}(b.fn.removeData));b.ui.ie=!!/msie [\w.]+/.exec(navigator.userAgent.toLowerCase());
b.support.selectstart="onselectstart"in document.createElement("div");b.fn.extend({disableSelection:function(){return this.bind((b.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(a){a.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});b.extend(b.ui,{plugin:{add:function(a,c,d){var e;a=b.ui[a].prototype;for(e in d)a.plugins[e]=a.plugins[e]||[],a.plugins[e].push([c,d[e]])},call:function(a,b,d){var e=a.plugins[b];if(e&&a.element[0].parentNode&&
11!==a.element[0].parentNode.nodeType)for(b=0;b<e.length;b++)a.options[e[b][0]]&&e[b][1].apply(a.element,d)}},hasScroll:function(a,c){if("hidden"===b(a).css("overflow"))return!1;var d=c&&"left"===c?"scrollLeft":"scrollTop",e=!1;if(0<a[d])return!0;a[d]=1;e=0<a[d];a[d]=0;return e}})})(f);return f})});
/* ******** */
(function(n){var m=window.AmazonUIPageJS||window.P,p=m._namespace||m.attributeErrors,k=p?p("JQueryUI_Widget_AUIBuild",""):m;k.guardFatal?k.guardFatal(n)(k,window):k.execute(function(){n(k,window)})})(function(n,m,p){n.when("jQuery").register("jQueryUI-widget",function(k){(function(c,k){var n=0,m=Array.prototype.slice,p=c.cleanData;c.cleanData=function(b){for(var a=0,f;null!=(f=b[a]);a++)try{c(f).triggerHandler("remove")}catch(d){}p(b)};c.widget=function(b,a,f){var d,e,g,h,q={},l=b.split(".")[0];b=
b.split(".")[1];d=l+"-"+b;f||(f=a,a=c.Widget);c.expr[":"][d.toLowerCase()]=function(a){return!!c.data(a,d)};c[l]=c[l]||{};e=c[l][b];g=c[l][b]=function(a,b){if(!this._createWidget)return new g(a,b);arguments.length&&this._createWidget(a,b)};c.extend(g,e,{version:f.version,_proto:c.extend({},f),_childConstructors:[]});h=new a;h.options=c.widget.extend({},h.options);c.each(f,function(b,d){c.isFunction(d)?q[b]=function(){var c=function(){return a.prototype[b].apply(this,arguments)},f=function(c){return a.prototype[b].apply(this,
c)};return function(){var b=this._super,a=this._superApply,e;this._super=c;this._superApply=f;e=d.apply(this,arguments);this._super=b;this._superApply=a;return e}}():q[b]=d});g.prototype=c.widget.extend(h,{widgetEventPrefix:e?h.widgetEventPrefix:b},q,{constructor:g,namespace:l,widgetName:b,widgetFullName:d});e?(c.each(e._childConstructors,function(b,a){var d=a.prototype;c.widget(d.namespace+"."+d.widgetName,g,a._proto)}),delete e._childConstructors):a._childConstructors.push(g);c.widget.bridge(b,
g)};c.widget.extend=function(b){for(var a=m.call(arguments,1),f=0,d=a.length,e,g;f<d;f++)for(e in a[f])g=a[f][e],a[f].hasOwnProperty(e)&&g!==k&&(c.isPlainObject(g)?b[e]=c.isPlainObject(b[e])?c.widget.extend({},b[e],g):c.widget.extend({},g):b[e]=g);return b};c.widget.bridge=function(b,a){var f=a.prototype.widgetFullName||b;c.fn[b]=function(d){var e="string"===typeof d,g=m.call(arguments,1),h=this;d=!e&&g.length?c.widget.extend.apply(null,[d].concat(g)):d;e?this.each(function(){var a,e=c.data(this,
f);if(!e)return c.error("cannot call methods on "+b+" prior to initialization; attempted to call method '"+d+"'");if(!c.isFunction(e[d])||"_"===d.charAt(0))return c.error("no such method '"+d+"' for "+b+" widget instance");a=e[d].apply(e,g);if(a!==e&&a!==k)return h=a&&a.jquery?h.pushStack(a.get()):a,!1}):this.each(function(){var b=c.data(this,f);b?b.option(d||{})._init():c.data(this,f,new a(d,this))});return h}};c.Widget=function(){};c.Widget._childConstructors=[];c.Widget.prototype={widgetName:"widget",
widgetEventPrefix:"",defaultElement:"\x3cdiv\x3e",options:{disabled:!1,create:null},_createWidget:function(b,a){a=c(a||this.defaultElement||this)[0];this.element=c(a);this.uuid=n++;this.eventNamespace="."+this.widgetName+this.uuid;this.options=c.widget.extend({},this.options,this._getCreateOptions(),b);this.bindings=c();this.hoverable=c();this.focusable=c();a!==this&&(c.data(a,this.widgetFullName,this),this._on(!0,this.element,{remove:function(b){b.target===a&&this.destroy()}}),this.document=c(a.style?
a.ownerDocument:a.document||a),this.window=c(this.document[0].defaultView||this.document[0].parentWindow));this._create();this._trigger("create",null,this._getCreateEventData());this._init()},_getCreateOptions:c.noop,_getCreateEventData:c.noop,_create:c.noop,_init:c.noop,destroy:function(){this._destroy();this.element.unbind(this.eventNamespace).removeData(this.widgetName).removeData(this.widgetFullName).removeData(c.camelCase(this.widgetFullName));this.widget().unbind(this.eventNamespace).removeAttr("aria-disabled").removeClass(this.widgetFullName+
"-disabled ui-state-disabled");this.bindings.unbind(this.eventNamespace);this.hoverable.removeClass("ui-state-hover");this.focusable.removeClass("ui-state-focus")},_destroy:c.noop,widget:function(){return this.element},option:function(b,a){var f=b,d,e,g;if(0===arguments.length)return c.widget.extend({},this.options);if("string"===typeof b)if(f={},d=b.split("."),b=d.shift(),d.length){e=f[b]=c.widget.extend({},this.options[b]);for(g=0;g<d.length-1;g++)e[d[g]]=e[d[g]]||{},e=e[d[g]];b=d.pop();if(a===
k)return e[b]===k?null:e[b];e[b]=a}else{if(a===k)return this.options[b]===k?null:this.options[b];f[b]=a}this._setOptions(f);return this},_setOptions:function(b){for(var a in b)this._setOption(a,b[a]);return this},_setOption:function(b,a){this.options[b]=a;"disabled"===b&&(this.widget().toggleClass(this.widgetFullName+"-disabled ui-state-disabled",!!a).attr("aria-disabled",a),this.hoverable.removeClass("ui-state-hover"),this.focusable.removeClass("ui-state-focus"));return this},enable:function(){return this._setOption("disabled",
!1)},disable:function(){return this._setOption("disabled",!0)},_on:function(b,a,f){var d,e=this;"boolean"!==typeof b&&(f=a,a=b,b=!1);f?(a=d=c(a),this.bindings=this.bindings.add(a)):(f=a,a=this.element,d=this.widget());c.each(f,function(f,h){function k(){if(b||!0!==e.options.disabled&&!c(this).hasClass("ui-state-disabled"))return("string"===typeof h?e[h]:h).apply(e,arguments)}"string"!==typeof h&&(k.guid=h.guid=h.guid||k.guid||c.guid++);var l=f.match(/^(\w+)\s*(.*)$/),m=l[1]+e.eventNamespace;(l=l[2])?
d.delegate(l,m,k):a.bind(m,k)})},_off:function(b,a){a=(a||"").split(" ").join(this.eventNamespace+" ")+this.eventNamespace;b.unbind(a).undelegate(a)},_delay:function(b,a){var c=this;return setTimeout(function(){return("string"===typeof b?c[b]:b).apply(c,arguments)},a||0)},_hoverable:function(b){this.hoverable=this.hoverable.add(b);this._on(b,{mouseenter:function(a){c(a.currentTarget).addClass("ui-state-hover")},mouseleave:function(a){c(a.currentTarget).removeClass("ui-state-hover")}})},_focusable:function(b){this.focusable=
this.focusable.add(b);this._on(b,{focusin:function(a){c(a.currentTarget).addClass("ui-state-focus")},focusout:function(a){c(a.currentTarget).removeClass("ui-state-focus")}})},_trigger:function(b,a,f){var d,e=this.options[b];f=f||{};a=c.Event(a);a.type=(b===this.widgetEventPrefix?b:this.widgetEventPrefix+b).toLowerCase();a.target=this.element[0];if(b=a.originalEvent)for(d in b)d in a||(a[d]=b[d]);this.element.trigger(a,f);return!(c.isFunction(e)&&!1===e.apply(this.element[0],[a].concat(f))||a.isDefaultPrevented())}};
c.each({show:"fadeIn",hide:"fadeOut"},function(b,a){c.Widget.prototype["_"+b]=function(f,d,e){"string"===typeof d&&(d={effect:d});var g,h=d?!0===d||"number"===typeof d?a:d.effect||a:b;d=d||{};"number"===typeof d&&(d={duration:d});g=!c.isEmptyObject(d);d.complete=e;d.delay&&f.delay(d.delay);if(g&&c.effects&&c.effects.effect[h])f[b](d);else if(h!==b&&f[h])f[h](d.duration,d.easing,e);else f.queue(function(a){c(this)[b]();e&&e.call(f[0]);a()})}})})(k);return k})});
/* ******** */
(function(t){var p=window.AmazonUIPageJS||window.P,r=p._namespace||p.attributeErrors,h=r?r("JQueryUI_Position_AUIBuild",""):p;h.guardFatal?h.guardFatal(t)(h,window):h.execute(function(){t(h,window)})})(function(t,p,r){t.when("jQuery").register("jQueryUI-position",function(h){(function(d,h){function t(a,b,c){return[parseFloat(a[0])*(y.test(a[0])?b/100:1),parseFloat(a[1])*(y.test(a[1])?c/100:1)]}function r(a){var b=a[0];return 9===b.nodeType?{width:a.width(),height:a.height(),offset:{top:0,left:0}}:
d.isWindow(b)?{width:a.width(),height:a.height(),offset:{top:a.scrollTop(),left:a.scrollLeft()}}:b.preventDefault?{width:0,height:0,offset:{top:b.pageY,left:b.pageX}}:{width:a.outerWidth(),height:a.outerHeight(),offset:a.offset()}}d.ui=d.ui||{};var u,A=Math.max,q=Math.abs,E=Math.round,z=/left|center|right/,B=/top|center|bottom/,C=/[\+\-]\d+(\.[\d]+)?%?/,F=/^\w+/,y=/%$/,G=d.fn.position;d.position={scrollbarWidth:function(){if(u!==h)return u;var a,b,c=d("\x3cdiv style\x3d'display:block;width:50px;height:50px;overflow:hidden;'\x3e\x3cdiv style\x3d'height:100px;width:auto;'\x3e\x3c/div\x3e\x3c/div\x3e");
b=c.children()[0];d("body").append(c);a=b.offsetWidth;c.css("overflow","scroll");b=b.offsetWidth;a===b&&(b=c[0].clientWidth);c.remove();return u=a-b},getScrollInfo:function(a){var b=a.isWindow?"":a.element.css("overflow-x"),c=a.isWindow?"":a.element.css("overflow-y"),b="scroll"===b||"auto"===b&&a.width<a.element[0].scrollWidth;return{width:"scroll"===c||"auto"===c&&a.height<a.element[0].scrollHeight?d.position.scrollbarWidth():0,height:b?d.position.scrollbarWidth():0}},getWithinInfo:function(a){a=
d(a||p);var b=d.isWindow(a[0]);return{element:a,isWindow:b,offset:a.offset()||{left:0,top:0},scrollLeft:a.scrollLeft(),scrollTop:a.scrollTop(),width:b?a.width():a.outerWidth(),height:b?a.height():a.outerHeight()}}};d.fn.position=function(a){if(!a||!a.of)return G.apply(this,arguments);a=d.extend({},a);var b,c,g,n,f,e,h=d(a.of),m=d.position.getWithinInfo(a.within),l=d.position.getScrollInfo(m),p=(a.collision||"flip").split(" "),u={};e=r(h);h[0].preventDefault&&(a.at="left top");c=e.width;g=e.height;
n=e.offset;f=d.extend({},n);d.each(["my","at"],function(){var b=(a[this]||"").split(" "),c,g;1===b.length&&(b=z.test(b[0])?b.concat(["center"]):B.test(b[0])?["center"].concat(b):["center","center"]);b[0]=z.test(b[0])?b[0]:"center";b[1]=B.test(b[1])?b[1]:"center";c=C.exec(b[0]);g=C.exec(b[1]);u[this]=[c?c[0]:0,g?g[0]:0];a[this]=[F.exec(b[0])[0],F.exec(b[1])[0]]});1===p.length&&(p[1]=p[0]);"right"===a.at[0]?f.left+=c:"center"===a.at[0]&&(f.left+=c/2);"bottom"===a.at[1]?f.top+=g:"center"===a.at[1]&&
(f.top+=g/2);b=t(u.at,c,g);f.left+=b[0];f.top+=b[1];return this.each(function(){var e,r,v=d(this),w=v.outerWidth(),x=v.outerHeight(),y=parseInt(d.css(this,"marginLeft"),10)||0,z=parseInt(d.css(this,"marginTop"),10)||0,B=w+y+(parseInt(d.css(this,"marginRight"),10)||0)+l.width,C=x+z+(parseInt(d.css(this,"marginBottom"),10)||0)+l.height,k=d.extend({},f),D=t(u.my,v.outerWidth(),v.outerHeight());"right"===a.my[0]?k.left-=w:"center"===a.my[0]&&(k.left-=w/2);"bottom"===a.my[1]?k.top-=x:"center"===a.my[1]&&
(k.top-=x/2);k.left+=D[0];k.top+=D[1];d.support.offsetFractions||(k.left=E(k.left),k.top=E(k.top));e={marginLeft:y,marginTop:z};d.each(["left","top"],function(f,n){if(d.ui.position[p[f]])d.ui.position[p[f]][n](k,{targetWidth:c,targetHeight:g,elemWidth:w,elemHeight:x,collisionPosition:e,collisionWidth:B,collisionHeight:C,offset:[b[0]+D[0],b[1]+D[1]],my:a.my,at:a.at,within:m,elem:v})});a.using&&(r=function(b){var d=n.left-k.left,e=d+c-w,f=n.top-k.top,m=f+g-x,l={target:{element:h,left:n.left,top:n.top,
width:c,height:g},element:{element:v,left:k.left,top:k.top,width:w,height:x},horizontal:0>e?"left":0<d?"right":"center",vertical:0>m?"top":0<f?"bottom":"middle"};c<w&&q(d+e)<c&&(l.horizontal="center");g<x&&q(f+m)<g&&(l.vertical="middle");A(q(d),q(e))>A(q(f),q(m))?l.important="horizontal":l.important="vertical";a.using.call(this,b,l)});v.offset(d.extend(k,{using:r}))})};d.ui.position={fit:{left:function(a,b){var c=b.within,g=c.isWindow?c.scrollLeft:c.offset.left,d=c.width,f=a.left-b.collisionPosition.marginLeft,
c=g-f,e=f+b.collisionWidth-d-g;b.collisionWidth>d?0<c&&0>=e?(g=a.left+c+b.collisionWidth-d-g,a.left+=c-g):a.left=0<e&&0>=c?g:c>e?g+d-b.collisionWidth:g:a.left=0<c?a.left+c:0<e?a.left-e:A(a.left-f,a.left)},top:function(a,b){var c=b.within,g=c.isWindow?c.scrollTop:c.offset.top,d=b.within.height,f=a.top-b.collisionPosition.marginTop,c=g-f,e=f+b.collisionHeight-d-g;b.collisionHeight>d?0<c&&0>=e?(g=a.top+c+b.collisionHeight-d-g,a.top+=c-g):a.top=0<e&&0>=c?g:c>e?g+d-b.collisionHeight:g:a.top=0<c?a.top+
c:0<e?a.top-e:A(a.top-f,a.top)}},flip:{left:function(a,b){var c=b.within,d=c.offset.left+c.scrollLeft,n=c.width,f=c.isWindow?c.scrollLeft:c.offset.left,e=a.left-b.collisionPosition.marginLeft,c=e-f,h=e+b.collisionWidth-n-f,e="left"===b.my[0]?-b.elemWidth:"right"===b.my[0]?b.elemWidth:0,m="left"===b.at[0]?b.targetWidth:"right"===b.at[0]?-b.targetWidth:0,l=-2*b.offset[0];if(0>c){if(d=a.left+e+m+l+b.collisionWidth-n-d,0>d||d<q(c))a.left+=e+m+l}else 0<h&&(d=a.left-b.collisionPosition.marginLeft+e+m+l-
f,0<d||q(d)<h)&&(a.left+=e+m+l)},top:function(a,b){var c=b.within,d=c.offset.top+c.scrollTop,n=c.height,f=c.isWindow?c.scrollTop:c.offset.top,e=a.top-b.collisionPosition.marginTop,c=e-f,h=e+b.collisionHeight-n-f,e="top"===b.my[1]?-b.elemHeight:"bottom"===b.my[1]?b.elemHeight:0,m="top"===b.at[1]?b.targetHeight:"bottom"===b.at[1]?-b.targetHeight:0,l=-2*b.offset[1];0>c?(d=a.top+e+m+l+b.collisionHeight-n-d,a.top+e+m+l>c&&(0>d||d<q(c))&&(a.top+=e+m+l)):0<h&&(d=a.top-b.collisionPosition.marginTop+e+m+l-
f,a.top+e+m+l>h&&(0<d||q(d)<h)&&(a.top+=e+m+l))}},flipfit:{left:function(){d.ui.position.flip.left.apply(this,arguments);d.ui.position.fit.left.apply(this,arguments)},top:function(){d.ui.position.flip.top.apply(this,arguments);d.ui.position.fit.top.apply(this,arguments)}}};(function(){var a,b,c,g,h=document.getElementsByTagName("body")[0];c=document.createElement("div");a=document.createElement(h?"div":"body");b={visibility:"hidden",width:0,height:0,border:0,margin:0,background:"none"};h&&d.extend(b,
{position:"absolute",left:"-1000px",top:"-1000px"});for(g in b)a.style[g]=b[g];a.appendChild(c);b=h||document.documentElement;b.insertBefore(a,b.firstChild);c.style.cssText="position: absolute; left: 10.7432222px;";c=d(c).offset().left;d.support.offsetFractions=10<c&&11>c;a.innerHTML="";b.removeChild(a)})()})(h);return h})});
/* ******** */
(function(g){var h=window.AmazonUIPageJS||window.P,k=h._namespace||h.attributeErrors,f=k?k("JQueryUI_Menu_AUIBuild",""):h;f.guardFatal?f.guardFatal(g)(f,window):f.execute(function(){g(f,window)})})(function(g,h,k){g.when("jQueryUI-core","jQueryUI-position","jQueryUI-widget").register("jQueryUI-menu",function(f){(function(d,f){d.widget("ui.menu",{version:"1.10.3",defaultElement:"\x3cul\x3e",delay:300,options:{icons:{submenu:"ui-icon-carat-1-e"},menus:"ul",position:{my:"left top",at:"right top"},role:"menu",
blur:null,focus:null,select:null},_create:function(){this.activeMenu=this.element;this.mouseHandled=!1;this.element.uniqueId().addClass("ui-menu ui-widget ui-widget-content ui-corner-all").toggleClass("ui-menu-icons",!!this.element.find(".ui-icon").length).attr({role:this.options.role,tabIndex:0}).bind("click"+this.eventNamespace,d.proxy(function(a){this.options.disabled&&a.preventDefault()},this));this.options.disabled&&this.element.addClass("ui-state-disabled").attr("aria-disabled","true");this._on({"mousedown .ui-menu-item \x3e a":function(a){a.preventDefault()},
"click .ui-state-disabled \x3e a":function(a){a.preventDefault()},"click .ui-menu-item:has(a)":function(a){var b=d(a.target).closest(".ui-menu-item");!this.mouseHandled&&b.not(".ui-state-disabled").length&&(this.mouseHandled=!0,this.select(a),b.has(".ui-menu").length?this.expand(a):this.element.is(":focus")||(this.element.trigger("focus",[!0]),this.active&&1===this.active.parents(".ui-menu").length&&clearTimeout(this.timer)))},"mouseenter .ui-menu-item":function(a){var b=d(a.currentTarget);b.siblings().children(".ui-state-active").removeClass("ui-state-active");
this.focus(a,b)},mouseleave:"collapseAll","mouseleave .ui-menu":"collapseAll",focus:function(a,b){var c=this.active||this.element.children(".ui-menu-item").eq(0);b||this.focus(a,c)},blur:function(a){this._delay(function(){d.contains(this.element[0],this.document[0].activeElement)||this.collapseAll(a)})},keydown:"_keydown"});this.refresh();this._on(this.document,{click:function(a){d(a.target).closest(".ui-menu").length||this.collapseAll(a);this.mouseHandled=!1}})},_destroy:function(){this.element.removeAttr("aria-activedescendant").find(".ui-menu").addBack().removeClass("ui-menu ui-widget ui-widget-content ui-corner-all ui-menu-icons").removeAttr("role").removeAttr("tabIndex").removeAttr("aria-labelledby").removeAttr("aria-expanded").removeAttr("aria-hidden").removeAttr("aria-disabled").removeUniqueId().show();
this.element.find(".ui-menu-item").removeClass("ui-menu-item").removeAttr("role").removeAttr("aria-disabled").children("a").removeUniqueId().removeClass("ui-corner-all ui-state-hover").removeAttr("tabIndex").removeAttr("role").removeAttr("aria-haspopup").children().each(function(){var a=d(this);a.data("ui-menu-submenu-carat")&&a.remove()});this.element.find(".ui-menu-divider").removeClass("ui-menu-divider ui-widget-content")},_keydown:function(a){function b(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,
"\\$\x26")}var c,e,f,g,h=!0;switch(a.keyCode){case d.ui.keyCode.PAGE_UP:this.previousPage(a);break;case d.ui.keyCode.PAGE_DOWN:this.nextPage(a);break;case d.ui.keyCode.HOME:this._move("first","first",a);break;case d.ui.keyCode.END:this._move("last","last",a);break;case d.ui.keyCode.UP:this.previous(a);break;case d.ui.keyCode.DOWN:this.next(a);break;case d.ui.keyCode.LEFT:this.collapse(a);break;case d.ui.keyCode.RIGHT:this.active&&!this.active.is(".ui-state-disabled")&&this.expand(a);break;case d.ui.keyCode.ENTER:case d.ui.keyCode.SPACE:this._activate(a);
break;case d.ui.keyCode.ESCAPE:this.collapse(a);break;default:h=!1,c=this.previousFilter||"",e=String.fromCharCode(a.keyCode),f=!1,clearTimeout(this.filterTimer),e===c?f=!0:e=c+e,g=new RegExp("^"+b(e),"i"),c=this.activeMenu.children(".ui-menu-item").filter(function(){return g.test(d(this).children("a").text())}),c=f&&-1!==c.index(this.active.next())?this.active.nextAll(".ui-menu-item"):c,c.length||(e=String.fromCharCode(a.keyCode),g=new RegExp("^"+b(e),"i"),c=this.activeMenu.children(".ui-menu-item").filter(function(){return g.test(d(this).children("a").text())})),
c.length?(this.focus(a,c),1<c.length?(this.previousFilter=e,this.filterTimer=this._delay(function(){delete this.previousFilter},1E3)):delete this.previousFilter):delete this.previousFilter}h&&a.preventDefault()},_activate:function(a){this.active.is(".ui-state-disabled")||(this.active.children("a[aria-haspopup\x3d'true']").length?this.expand(a):this.select(a))},refresh:function(){var a,b=this.options.icons.submenu;a=this.element.find(this.options.menus);a.filter(":not(.ui-menu)").addClass("ui-menu ui-widget ui-widget-content ui-corner-all").hide().attr({role:this.options.role,
"aria-hidden":"true","aria-expanded":"false"}).each(function(){var a=d(this),e=a.prev("a"),f=d("\x3cspan\x3e").addClass("ui-menu-icon ui-icon "+b).data("ui-menu-submenu-carat",!0);e.attr("aria-haspopup","true").prepend(f);a.attr("aria-labelledby",e.attr("id"))});a=a.add(this.element);a.children(":not(.ui-menu-item):has(a)").addClass("ui-menu-item").attr("role","presentation").children("a").uniqueId().addClass("ui-corner-all").attr({tabIndex:-1,role:this._itemRole()});a.children(":not(.ui-menu-item)").each(function(){var a=
d(this);/[^\-\u2014\u2013\s]/.test(a.text())||a.addClass("ui-widget-content ui-menu-divider")});a.children(".ui-state-disabled").attr("aria-disabled","true");this.active&&!d.contains(this.element[0],this.active[0])&&this.blur()},_itemRole:function(){return{menu:"menuitem",listbox:"option"}[this.options.role]},_setOption:function(a,b){"icons"===a&&this.element.find(".ui-menu-icon").removeClass(this.options.icons.submenu).addClass(b.submenu);this._super(a,b)},focus:function(a,b){var c;this.blur(a,a&&
"focus"===a.type);this._scrollIntoView(b);this.active=b.first();c=this.active.children("a").addClass("ui-state-focus");this.options.role&&this.element.attr("aria-activedescendant",c.attr("id"));this.active.parent().closest(".ui-menu-item").children("a:first").addClass("ui-state-active");a&&"keydown"===a.type?this._close():this.timer=this._delay(function(){this._close()},this.delay);c=b.children(".ui-menu");c.length&&/^mouse/.test(a.type)&&this._startOpening(c);this.activeMenu=b.parent();this._trigger("focus",
a,{item:b})},_scrollIntoView:function(a){var b,c,e;this._hasScroll()&&(b=parseFloat(d.css(this.activeMenu[0],"borderTopWidth"))||0,c=parseFloat(d.css(this.activeMenu[0],"paddingTop"))||0,b=a.offset().top-this.activeMenu.offset().top-b-c,c=this.activeMenu.scrollTop(),e=this.activeMenu.height(),a=a.height(),0>b?this.activeMenu.scrollTop(c+b):b+a>e&&this.activeMenu.scrollTop(c+b-e+a))},blur:function(a,b){b||clearTimeout(this.timer);this.active&&(this.active.children("a").removeClass("ui-state-focus"),
this.active=null,this._trigger("blur",a,{item:this.active}))},_startOpening:function(a){clearTimeout(this.timer);"true"===a.attr("aria-hidden")&&(this.timer=this._delay(function(){this._close();this._open(a)},this.delay))},_open:function(a){var b=d.extend({of:this.active},this.options.position);clearTimeout(this.timer);this.element.find(".ui-menu").not(a.parents(".ui-menu")).hide().attr("aria-hidden","true");a.show().removeAttr("aria-hidden").attr("aria-expanded","true").position(b)},collapseAll:function(a,
b){clearTimeout(this.timer);this.timer=this._delay(function(){var c=b?this.element:d(a&&a.target).closest(this.element.find(".ui-menu"));c.length||(c=this.element);this._close(c);this.blur(a);this.activeMenu=c},this.delay)},_close:function(a){a||(a=this.active?this.active.parent():this.element);a.find(".ui-menu").hide().attr("aria-hidden","true").attr("aria-expanded","false").end().find("a.ui-state-active").removeClass("ui-state-active")},collapse:function(a){var b=this.active&&this.active.parent().closest(".ui-menu-item",
this.element);b&&b.length&&(this._close(),this.focus(a,b))},expand:function(a){var b=this.active&&this.active.children(".ui-menu ").children(".ui-menu-item").first();b&&b.length&&(this._open(b.parent()),this._delay(function(){this.focus(a,b)}))},next:function(a){this._move("next","first",a)},previous:function(a){this._move("prev","last",a)},isFirstItem:function(){return this.active&&!this.active.prevAll(".ui-menu-item").length},isLastItem:function(){return this.active&&!this.active.nextAll(".ui-menu-item").length},
_move:function(a,b,c){var d;this.active&&(d="first"===a||"last"===a?this.active["first"===a?"prevAll":"nextAll"](".ui-menu-item").eq(-1):this.active[a+"All"](".ui-menu-item").eq(0));d&&d.length&&this.active||(d=this.activeMenu.children(".ui-menu-item")[b]());this.focus(c,d)},nextPage:function(a){var b,c,e;this.active?this.isLastItem()||(this._hasScroll()?(c=this.active.offset().top,e=this.element.height(),this.active.nextAll(".ui-menu-item").each(function(){b=d(this);return 0>b.offset().top-c-e}),
this.focus(a,b)):this.focus(a,this.activeMenu.children(".ui-menu-item")[this.active?"last":"first"]())):this.next(a)},previousPage:function(a){var b,c,e;this.active?this.isFirstItem()||(this._hasScroll()?(c=this.active.offset().top,e=this.element.height(),this.active.prevAll(".ui-menu-item").each(function(){b=d(this);return 0<b.offset().top-c+e}),this.focus(a,b)):this.focus(a,this.activeMenu.children(".ui-menu-item").first())):this.next(a)},_hasScroll:function(){return this.element.outerHeight()<
this.element.prop("scrollHeight")},select:function(a){this.active=this.active||d(a.target).closest(".ui-menu-item");var b={item:this.active};this.active.has(".ui-menu").length||this.collapseAll(a,!0);this._trigger("select",a,b)}})})(f)})});
/* ******** */
(function(h){var l=window.AmazonUIPageJS||window.P,m=l._namespace||l.attributeErrors,g=m?m("JQueryUI_Autocomplete_AUIBuild",""):l;g.guardFatal?g.guardFatal(h)(g,window):g.execute(function(){h(g,window)})})(function(h,l,m){h.when("jQueryUI-core","jQueryUI-position","jQueryUI-widget","jQueryUI-menu").register("jQueryUI-autocomplete",function(g){(function(c,g){var h=0;c.widget("ui.autocomplete",{version:"1.10.3",defaultElement:"\x3cinput\x3e",options:{appendTo:null,autoFocus:!1,delay:300,minLength:1,
position:{my:"left top",at:"left bottom",collision:"none"},source:null,change:null,close:null,focus:null,open:null,response:null,search:null,select:null},pending:0,_create:function(){var a,b,e,k=this.element[0].nodeName.toLowerCase(),n="textarea"===k,k="input"===k;this.isMultiLine=n?!0:k?!1:this.element.prop("isContentEditable");this.valueMethod=this.element[n||k?"val":"text"];this.isNewMenu=!0;this.element.addClass("ui-autocomplete-input").attr("autocomplete","off");this._on(this.element,{keydown:function(d){if(this.element.prop("readOnly"))b=
e=a=!0;else{b=e=a=!1;var f=c.ui.keyCode;switch(d.keyCode){case f.PAGE_UP:a=!0;this._move("previousPage",d);break;case f.PAGE_DOWN:a=!0;this._move("nextPage",d);break;case f.UP:a=!0;this._keyEvent("previous",d);break;case f.DOWN:a=!0;this._keyEvent("next",d);break;case f.ENTER:case f.NUMPAD_ENTER:this.menu.active&&(a=!0,d.preventDefault(),this.menu.select(d));break;case f.TAB:this.menu.active&&this.menu.select(d);break;case f.ESCAPE:this.menu.element.is(":visible")&&(this._value(this.term),this.close(d),
d.preventDefault());break;default:b=!0,this._searchTimeout(d)}}},keypress:function(d){if(a)a=!1,this.isMultiLine&&!this.menu.element.is(":visible")||d.preventDefault();else if(!b){var f=c.ui.keyCode;switch(d.keyCode){case f.PAGE_UP:this._move("previousPage",d);break;case f.PAGE_DOWN:this._move("nextPage",d);break;case f.UP:this._keyEvent("previous",d);break;case f.DOWN:this._keyEvent("next",d)}}},input:function(a){e?(e=!1,a.preventDefault()):this._searchTimeout(a)},focus:function(){this.selectedItem=
null;this.previous=this._value()},blur:function(a){this.cancelBlur?delete this.cancelBlur:(clearTimeout(this.searching),this.close(a),this._change(a))}});this._initSource();this.menu=c("\x3cul\x3e").addClass("ui-autocomplete ui-front").appendTo(this._appendTo()).menu({role:null}).hide().data("ui-menu");this._on(this.menu.element,{mousedown:function(a){a.preventDefault();this.cancelBlur=!0;this._delay(function(){delete this.cancelBlur});var b=this.menu.element[0];c(a.target).closest(".ui-menu-item").length||
this._delay(function(){var a=this;this.document.one("mousedown",function(d){d.target===a.element[0]||d.target===b||c.contains(b,d.target)||a.close()})})},menufocus:function(a,b){if(this.isNewMenu&&(this.isNewMenu=!1,a.originalEvent&&/^mouse/.test(a.originalEvent.type))){this.menu.blur();this.document.one("mousemove",function(){c(a.target).trigger(a.originalEvent)});return}var e=b.item.data("ui-autocomplete-item");!1!==this._trigger("focus",a,{item:e})?a.originalEvent&&/^key/.test(a.originalEvent.type)&&
this._value(e.value):this.liveRegion.text(e.value)},menuselect:function(a,b){var c=b.item.data("ui-autocomplete-item"),e=this.previous;this.element[0]!==this.document[0].activeElement&&(this.element.focus(),this.previous=e,this._delay(function(){this.previous=e;this.selectedItem=c}));!1!==this._trigger("select",a,{item:c})&&this._value(c.value);this.term=this._value();this.close(a);this.selectedItem=c}});this.liveRegion=c("\x3cspan\x3e",{role:"status","aria-live":"polite"}).addClass("ui-helper-hidden-accessible").insertBefore(this.element);
this._on(this.window,{beforeunload:function(){this.element.removeAttr("autocomplete")}})},_destroy:function(){clearTimeout(this.searching);this.element.removeClass("ui-autocomplete-input").removeAttr("autocomplete");this.menu.element.remove();this.liveRegion.remove()},_setOption:function(a,b){this._super(a,b);"source"===a&&this._initSource();"appendTo"===a&&this.menu.element.appendTo(this._appendTo());"disabled"===a&&b&&this.xhr&&this.xhr.abort()},_appendTo:function(){var a=this.options.appendTo;
a&&(a=a.jquery||a.nodeType?c(a):this.document.find(a).eq(0));a||(a=this.element.closest(".ui-front"));a.length||(a=this.document[0].body);return a},_initSource:function(){var a,b,e=this;c.isArray(this.options.source)?(a=this.options.source,this.source=function(b,e){e(c.ui.autocomplete.filter(a,b.term))}):"string"===typeof this.options.source?(b=this.options.source,this.source=function(a,g){e.xhr&&e.xhr.abort();e.xhr=c.ajax({url:b,data:a,dataType:"json",success:function(a){g(a)},error:function(){g([])}})}):
this.source=this.options.source},_searchTimeout:function(a){clearTimeout(this.searching);this.searching=this._delay(function(){this.term!==this._value()&&(this.selectedItem=null,this.search(null,a))},this.options.delay)},search:function(a,b){a=null!=a?a:this._value();this.term=this._value();if(a.length<this.options.minLength)return this.close(b);if(!1!==this._trigger("search",b))return this._search(a)},_search:function(a){this.pending++;this.element.addClass("ui-autocomplete-loading");this.cancelSearch=
!1;this.source({term:a},this._response())},_response:function(){var a=this,b=++h;return function(c){b===h&&a.__response(c);a.pending--;a.pending||a.element.removeClass("ui-autocomplete-loading")}},__response:function(a){a&&(a=this._normalize(a));this._trigger("response",null,{content:a});!this.options.disabled&&a&&a.length&&!this.cancelSearch?(this._suggest(a),this._trigger("open")):this._close()},close:function(a){this.cancelSearch=!0;this._close(a)},_close:function(a){this.menu.element.is(":visible")&&
(this.menu.element.hide(),this.menu.blur(),this.isNewMenu=!0,this._trigger("close",a))},_change:function(a){this.previous!==this._value()&&this._trigger("change",a,{item:this.selectedItem})},_normalize:function(a){return a.length&&a[0].label&&a[0].value?a:c.map(a,function(a){return"string"===typeof a?{label:a,value:a}:c.extend({label:a.label||a.value,value:a.value||a.label},a)})},_suggest:function(a){var b=this.menu.element.empty();this._renderMenu(b,a);this.isNewMenu=!0;this.menu.refresh();b.show();
this._resizeMenu();b.position(c.extend({of:this.element},this.options.position));this.options.autoFocus&&this.menu.next()},_resizeMenu:function(){var a=this.menu.element;a.outerWidth(Math.max(a.width("").outerWidth()+1,this.element.outerWidth()))},_renderMenu:function(a,b){var e=this;c.each(b,function(b,c){e._renderItemData(a,c)})},_renderItemData:function(a,b){return this._renderItem(a,b).data("ui-autocomplete-item",b)},_renderItem:function(a,b){return c("\x3cli\x3e").append(c("\x3ca\x3e").text(b.label)).appendTo(a)},
_move:function(a,b){if(this.menu.element.is(":visible"))if(this.menu.isFirstItem()&&/^previous/.test(a)||this.menu.isLastItem()&&/^next/.test(a))this._value(this.term),this.menu.blur();else this.menu[a](b);else this.search(null,b)},widget:function(){return this.menu.element},_value:function(){return this.valueMethod.apply(this.element,arguments)},_keyEvent:function(a,b){if(!this.isMultiLine||this.menu.element.is(":visible"))this._move(a,b),b.preventDefault()}});c.extend(c.ui.autocomplete,{escapeRegex:function(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,
"\\$\x26")},filter:function(a,b){var e=new RegExp(c.ui.autocomplete.escapeRegex(b),"i");return c.grep(a,function(a){return e.test(a.label||a.value||a)})}});c.widget("ui.autocomplete",c.ui.autocomplete,{options:{messages:{noResults:"No search results.",results:function(a){return a+(1<a?" results are":" result is")+" available, use up and down arrow keys to navigate."}}},__response:function(a){var b;this._superApply(arguments);this.options.disabled||this.cancelSearch||(b=a&&a.length?this.options.messages.results(a.length):
this.options.messages.noResults,this.liveRegion.text(b))}})})(g)})});
/* ******** */
(function(f){var l=window.AmazonUIPageJS||window.P,n=l._namespace||l.attributeErrors,b=n?n("JQuery_Cookie_AUIBuild"):l;b.guardFatal?b.guardFatal(f)(b,window):b.execute(function(){f(b,window)})})(function(f,l,n){f.when("jQuery").register("jQuery-Cookie",function(b){(function(a){"function"===typeof define&&define.amd?define(["jquery"],a):a(b)})(function(a){function b(a){return f.raw?a:decodeURIComponent(a.replace(d," "))}function e(a){0===a.indexOf('"')&&(a=a.slice(1,-1).replace(/\\"/g,'"').replace(/\\\\/g,
"\\"));a=b(a);try{return f.json?JSON.parse(a):a}catch(d){}}var d=/\+/g,f=a.cookie=function(d,l,g){if(l!==n){g=a.extend({},f.defaults,g);if("number"===typeof g.expires){var u=g.expires,D=g.expires=new Date;D.setDate(D.getDate()+u)}l=f.json?JSON.stringify(l):String(l);return document.cookie=[f.raw?d:encodeURIComponent(d),"=",f.raw?l:encodeURIComponent(l),g.expires?"; expires="+g.expires.toUTCString():"",g.path?"; path="+g.path:"",g.domain?"; domain="+g.domain:"",g.secure?"; secure":""].join("")}l=document.cookie.split("; ");
g=d?n:{};u=0;for(D=l.length;u<D;u++){var v=l[u].split("="),r=b(v.shift()),v=v.join("=");if(d&&d===r){g=e(v);break}d||(g[r]=e(v))}return g};f.defaults={};a.removeCookie=function(b,c){return a.cookie(b)!==n?(a.cookie(b,"",a.extend({},c,{expires:-1})),!0):!1}})})});
/* ******** */
(function(f){var l=window.AmazonUIPageJS||window.P,n=l._namespace||l.attributeErrors,b=n?n("AuthenticationPortalAssets"):l;b.guardFatal?b.guardFatal(f)(b,window):b.execute(function(){f(b,window)})})(function(f,l,n){f.when("A","cvf","ready").register("auth-account-switcher",function(b,a){function c(a){return n}function e(a){l.location=d(l.location);return n}function d(a){var b=a.search;return b?b.match(k)?a.href.replace(k,"$1ACCOUNT_SWITCH_FAILED"):a.href+"&errorCodes=ACCOUNT_SWITCH_FAILED":a.href+
"?errorCodes=ACCOUNT_SWITCH_FAILED"}var h=b.$,k=/(errorCodes=)[\w\d]+/g;h("#ap-account-switcher-container").length&&"undefined"!==typeof h("#ap-account-switcher-container").attr("data-token")&&(h={target:h("#ap-account-switcher-container"),requestToken:h("#ap-account-switcher-container").attr("data-token"),requestArbToken:h("#ap-account-switcher-container").attr("data-arbToken"),onSuccess:c,onError:e,autoStart:!1,widgetMetricsScope:"CvfAccountSwitcherClientSideMetrics"},a.create(h).start());return{getUrlWithSwitchErrorCodeAdded:d}});
f.when("A","ready").register("auth-login-autofill",function(b){function a(a){var b=a.data("claim");a.val()!==b&&a.val(b)}function c(a,b){var c=e(a);c.change(function(){b(e(this))});b(c)}var e=b.$;c("#ap-credential-autofill-hint",a);return{monitorForChanges:c,restoreClaimValue:a}});f.register("AmazonHelpPopup",function(){return function(b,a,c){l.open(b,a,c).focus();return!1}});f.when("A","ready").execute(function(b){b.$(".auth-autofocus").first().focus()});
f.when("A","ready").execute(function(b){function a(){location.href=e.returnToAddress}function c(){clearTimeout(d);d=setTimeout(a,h)}var e=b.state("timeout-parameters");if(e){var d=0,h=e.timeoutValue;document.onmousemove=c;document.onkeypress=c;document.ontouchstart=c;document.ontouchmove=c;document.ontouchend=c;c()}});f.when("A","auth-captcha-cf").register("auth-image-captcha",function(b){function a(a){a&&a.captchaImageUrl&&d.test(a.captchaImageUrl)?(e("#auth-captcha-image").attr("src",
a.captchaImageUrl),e("input[type='hidden'][name='ces']").val(a.cesString)):(f.log("Failed to load new CAPTCHA due to invalid response from server","FATAL","auth-captcha"),l.location.reload(!0))}function c(){e("#auth-captcha-refresh-link").hide();e("#auth-captcha-noop-link").show();e("#auth-captcha-image").hide();e("#auth-captcha-image-container").addClass("a-lazy-loaded");var a=e("#auth-captcha-image").attr("data-refresh-url");a||f.log("Attempting to instantiate Captcha without a valid refresh url.",
"FATAL","auth-captcha");b.ajax(a,h)}var e=b.$,d=/^(http|https):\/\//,h={cache:!1,timeout:1E3,error:function(){f.log("Failed to refresh CAPTCHA due to error response from server","FATAL","auth-captcha");l.location.reload(!0)},success:a};e("#auth-captcha-image").load(function(){e("#auth-captcha-noop-link").hide();e("#auth-captcha-refresh-link").show();e("#auth-captcha-image-container").removeClass("a-lazy-loaded");e("#auth-captcha-image").fadeIn()});e(document).delegate("#auth-captcha-refresh-link",
"click",function(a){a.preventDefault();c();e("#auth-captcha-guess").focus()});return{handleSuccess:a,refresh:c}});f.when("A","auth-image-captcha","ready").register("auth-audio-captcha-handler",function(b,a){function c(a){a&&a.captchaImageUrl&&B.test(a.captchaImageUrl)?(k.val(a.cesString),n.attr("src",a.captchaImageUrl),h.load()):(f.log("Failed to load new CAPTCHA due to invalid response from server","FATAL","auth-audio-captcha-handler"),l.location.reload(!0))}function e(){b.ajax(n.attr("data-refresh-url"),
C);y.focus()}var d=b.$,h=d("#audio-captcha")[0],k=d("input[type='hidden'][name='ces']"),m=d("#audio-captcha-section"),g=d("#auth-captcha-guess"),u=d("#image-captcha-section"),n=d("#mp3-file"),v=d("#auth-switch-captcha-to-audio-container"),r=d("#use_audio_captcha"),t=d("#use_image_captcha");d("#auth-error-message-box");var B=/^(http|https):\/\//,p=d(".a-mobile").length,y=d("#audio-captcha-play-pause-button"),w=d("#audio-captcha-options"),q=d("#image-captcha-options"),A=d("#image-captcha-placeholder"),
z=d("#audio-captcha-placeholder"),C={cache:!1,timeout:1E3,error:function(){f.log("Failed to refresh CAPTCHA due to error response from server","FATAL","auth-audio-captcha-handler");l.location.reload(!0)},success:c};b.capabilities.audio&&v.show();return{switchCaptchaToAudio:function(){u.hide();t.val("false");m.show();r.val("true");g.val("");e();p&&(q.hide(),w.show(),g.attr("placeholder",z.val()))},switchCaptchaToImage:function(){m.hide();r.val("false");u.show();t.val("true");g.val("");h.pause();a.refresh();
g.focus();p&&(q.show(),w.hide(),g.attr("placeholder",A.val()))},audioRefresh:e,audioPlayButton:function(){h.paused?(g.focus(),h.play()):h.pause()},handleSuccess:c}});f.when("A","auth-audio-captcha-handler","ready").register("auth-audio-captcha",function(b,a){var c=b.$;c("#auth-switch-captcha-to-audio").click(function(b){b.preventDefault();a.switchCaptchaToAudio()});c("#auth-switch-captcha-to-image").click(function(b){b.preventDefault();a.switchCaptchaToImage()});c("#auth-refresh-audio").click(function(b){b.preventDefault();
a.audioRefresh()});c("#audio-captcha-play-pause-button").click(function(b){b.preventDefault();a.audioPlayButton()});return{handleSuccess:a.handleSuccess}});f.when("A").register("auth-cookie",function(b){function a(a,c,e){if(a){var f="";b.isFiniteNumber(e)&&(0>e?f="; expires=Thu, 01 Jan 1970 00:00:00 GMT":(f=new Date,f.setDate(f.getDate()+e),f="; expires="+f.toGMTString()));document.cookie=a+"="+l.encodeURIComponent(c)+f;return!0}return!1}function c(a){if(0<document.cookie.length&&a){var b=
document.cookie.indexOf(a+"=");if(-1<b)return b=b+a.length+1,a=document.cookie.indexOf(";",b),-1===a&&(a=document.cookie.length),l.decodeURIComponent(document.cookie.substring(b,a))}return""}function e(b){a(b,"",-1)}return{setCookie:a,getCookieValue:c,deleteCookie:e,checkCookieEnabled:function(b){a("amznTest","1");var h=c("amznTest");h?e("amznTest"):b&&(b=document.getElementById(b))&&(b.style.display="block");return!!h}}});f.when("A","ready").register("auth-pv-resend-utility",function(b){return{successHandler:function(a,
b){a.show();b.show()},errorHandler:function(a,b,e,d,h){403===a.http.status?l.location=b.sessionTimeoutUrl:(0<=(a.http.response||"").search("Throttled")?e.show():d.show(),h.show())},hideMessageBox:function(a,b,e,d,h){a.hide();b.hide();e.hide();d.hide();h.hide()}}});f.when("A","auth-pv-resend-utility","ready").register("auth-pv-resend",function(b,a){var c=b.state("auth-pv-page-state");if(c){var e=b.$,d=e("#auth-pv-client-side-success-box"),h=e(".auth-pv-client-side-success-messages li"),f=e("#auth-pv-client-side-error-box"),
l=e(".auth-pv-client-side-error-messages li"),g=e(".auth-server-side-message-box"),u=e("#auth-resend-code-succeeded"),n=e("#auth-there-was-an-error-throttled"),v=e("#auth-there-was-an-error"),r=function(){a.successHandler(u,d)},t=function(b){a.errorHandler(b,c,n,v,f)};e("#auth-resend-code-link").click(function(e){a.hideMessageBox(d,h,f,l,g);b.ajax(c.resendUrl,{method:"post",success:r,error:t})});return{successHandler:r,errorHandler:t}}});f.when("A").register("auto-verification-timeout",function(b){var a=
b.$,c=a("#auth-auto-verification-failed");c.length&&b.delay(function(){c[0].click()},3E4)});f.when("A","AmazonHelpPopup","ready").execute(function(b,a){b.$("#auth-amazon-help-link").click(function(){return a(this.href,"AmazonHelp","width=700,height=800,resizable=1,scrollbars=1,toolbar=1,status=1")})});f.when("A").execute(function(b){b.declarative("auth-popup","click",function(a){var b=a.data;a=a.$target.closest("a")[0];(b=l.open(a.href,a.target,b.windowOptions))&&b.focus()})});f.when("auth-cookie",
"ready").execute(function(b){b.checkCookieEnabled("auth-cookie-warning-message")});f.when("A","ready").register("AuthToolkit",function(b){function a(a){"undefined"!==typeof d(a)&&d(a).hasClass("a-button-disabled")&&(d(a).removeClass("a-button-disabled"),e(a).attr("disabled",!1))}function c(h,f){var l=e(h),g=l.data("remaining"),u=l.data("unit");0===g?(a(h),d(h).find(".a-button-text").text(f),b.trigger("AuthToolkit.countDownEnd",h)):0<g&&(l.data("remaining",g-1),d(h).find(".a-button-text").text(u.replace(/%d/,
g)),b.delay(function(){c(h,f)},1E3))}function e(a){var b=d(a).find("button");return 0<b.length?b:d(a).find("input")}var d=b.$;return{disableButton:function(a){"undefined"===typeof d(a)||d(a).hasClass("a-button-disabled")||(d(a).addClass("a-button-disabled"),e(a).attr("disabled","disabled"))},enableButton:a,countingDown:function(a){if("undefined"!==typeof d(a)){var b=d(a).find(".a-button-text").text();0<=e(a).data("remaining")&&c(a,b)}}}});f.when("A","ready").execute(function(b){var a=
b.$("#auth-external-javascript").data("external-javascripts");a&&a.length&&b.each(a,function(a){f.load.js(a,function(a){a.target.setAttribute("crossorigin","anonymous")})})});f.when("A","a-modal","auth-validate-form-handler","ready").register("auth-phone-verification-modal",function(b,a,c){function e(){var a=l.val();v.text(a);var b=f.find("option:selected"),a=b.data("calling-code"),b=b.data("country-code");u.text(a);n.text(b)}var d=b.$,h=b.state("auth-phone-verification-modal");if(h){var f=
d("#auth-country-picker"),l=d("#ap_phone_number"),g=d("#"+h.formIdToBindTo),u=d("#auth-verify-mobile-calling-code"),n=d("#auth-verify-mobile-country-code"),v=d("#auth-verify-mobile-national-number");b.on("a:popover:beforeShow:verifyContinueModal",e);d(".auth-requires-verify-modal").click(function(b){b.preventDefault();c.validate(g)&&(b=d("#auth-verify-modal-action"),(b=a.get(b))&&l.is(":enabled")?b.show():g.submit())});b.declarative("auth-verify-modal-complete","click",function(){g.submit()});return{updateVerificationModalContents:e}}});
f.when("A").register("auth-phone-verification-spinner",function(b){b=b.$;var a=b("#auth-contact-verification-spinner-hidden-code-form-wrapper #auth-pv-form");0<a.length&&(l.submitVerificationCode=function(b){a.find("#auth-pv-enter-code").val(b);a.find("#auth-verify-button").click()})});f.when("A","auth-validate-form-common","a-form-controls-api","client-side-counters-util","page-util","ready").register("auth-moa",function(b,a,c,e,d){var h=b.$,f=h("#ap_phone_number"),l=h("#ap_email");
h("#ap_use_mobile, #ap_use_email").click(function(a){h(".ap_email_fields,.ap_mobile_number_fields").toggle();h("#auth-country-picker, #ap_email, #ap_phone_number").prop("disabled",function(a,b){return!b});h("#auth-country-picker-container").toggleClass("a-button-disabled");d.isMobile()?h("#ap_email, #ap_phone_number").parent(".a-input-text-wrapper").toggleClass("a-form-disabled"):h("#ap_email, #ap_phone_number").toggleClass("a-form-disabled");return!1});h("#ap_use_email").click(function(){a.isNonBlankField(f)&&
a.isValidEmailField(f)&&(l.val(f.val()).keyup(),e.incrementCounter("PersistEmailFromPhoneToEmail"+d.determineDeviceType()))});h("#ap_use_mobile").click(function(){a.isNonBlankField(l)&&a.isValidPhoneNumberField(l)&&(f.val(l.val()).keyup(),e.incrementCounter("PersistPhoneFromEmailToPhone"+d.determineDeviceType()))})});f.when("A","page-util","ready").register("auth-validate-form-common",function(b,a){function c(a){return g.test(a.trim())}function e(a){return!u.test(a.trim())}function d(a){return a.data("validation-id")||
a.parent().data("validation-id")||a[0].name}function h(a){var b=a.closest(".a-input-text-wrapper");0<b.length?b.addClass("a-form-error"):a.addClass("a-form-error")}function f(a){var b=a.closest(".a-input-text-wrapper");0<b.length?b.removeClass("a-form-error"):a.removeClass("a-form-error")}var l=b.$,g=/^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,u=/^ *\+|^ *＋|[a-zA-ZＡ-Ｚａ-ｚ]|@/,n=/[a-zA-Z]/,v={"auth-required-field":"-missing-alert","auth-require-email-validaton":"-invalid-email-alert",
"auth-require-phone-validation":"-invalid-phone-alert","auth-require-claim-validation":"-invalid-claim-alert","auth-require-password-validation":"-invalid-password-alert","auth-require-fields-match":"-mismatch-alert"};return{isMatchingFields:function(a){var b=a.eq(0);a=a.eq(1);b=b.val().trim();a=a.val().trim();return b===a},isValidEmailField:function(a){a=a.val();return c(a)},isValidPhoneNumberField:function(a){a=a.val();return e(a)},isValidClaimField:function(a){a=a.val();return c(a)||!n.test(a.trim())},
isValidEmail:c,isValidPhoneWithCountryCodeSelector:e,isValidPasswordField:function(a){return 6<=a.val().length},isNonEmptyField:function(a){return!!a.val()},isNonBlankField:function(a){return!!a.val().trim()},displayErrorMessage:function(a,b){var c=d(a),c=l("#auth-"+c+b);h(a);c.show()},hideErrorMessage:function(a,b){var c=d(a),c=l("#auth-"+c+b);f(a);c.hide()},isErrorVisible:function(a,b){var c=d(a);return l("#auth-"+c+v[b]).is(":visible")},getValidationId:d,addErrorClass:h,removeErrorClass:f,determineDeviceType:function(){return a.isMobile()?
"OnMobile":"OnDesktop"},getErrorAlertExtension:function(a){return v[a]},getSelectorForInputsOfErrorTypeClass:function(a){if(a)return a+=":visible","input:enabled."+a+", ."+a+" input:enabled"}}});f.when("A","auth-validate-form-common","client-side-counters-util","page-util","ready").register("auth-validate-form-handler",function(b,a,c,e){function d(b,d,g,h){var f=a.getValidationId(d);f&&(q||(q={}),q[f]||(q[f]=[]),q[f].push({$field:d,type:g,extension:h}),h&&c.incrementCounter(e.getFormName(b)+
e.toCamelCase(f+h)+a.determineDeviceType()))}function h(b){b.find(".auth-require-fields-match-group").each(function(){var c=p(this).find(a.getSelectorForInputsOfErrorTypeClass("auth-require-fields-match"));1<c.length&&v(c.eq(0))&&v(c.eq(1))&&!a.isMatchingFields(c)&&(d(b,c.eq(0),"Check Mismatch","-mismatch-alert"),d(b,c.eq(1),"Check Mismatch"))})}function f(b){b.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-email-validaton")).each(function(){var c=p(this);a.isNonBlankField(c)&&!a.isValidEmailField(c)&&
d(b,c,"Invalid Email","-invalid-email-alert")})}function l(b){b.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-claim-validation")).each(function(){var c=p(this);a.isNonBlankField(c)&&!a.isValidClaimField(c)&&d(b,c,"Invalid Claim","-invalid-claim-alert")})}function g(b){b.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-phone-validation")).each(function(){var c=p(this);a.isNonBlankField(c)&&!a.isValidPhoneNumberField(c)&&d(b,c,"Invalid Phone","-invalid-phone-alert")})}function u(b){b.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-password-validation")).each(function(){var c=
p(this);a.isNonEmptyField(c)&&!a.isValidPasswordField(c)&&d(b,c,"Invalid Password","-invalid-password-alert")})}function n(b){b.find(a.getSelectorForInputsOfErrorTypeClass("auth-required-field")).each(function(){var a=p(this),c=this.name;v(a)||y.test(c)&&q&&q[c.split("Check")[0]]||d(b,a,"Missing Required","-missing-alert")})}function v(b){return"password"===b.attr("type")?a.isNonEmptyField(b):a.isNonBlankField(b)}function r(c){var d=p("#auth-alert-window");c.find(".a-form-error").removeClass("a-form-error");
p(".auth-error-messages li, .auth-inlined-error-message, .auth-inlined-information-message, .auth-server-side-message-box").hide();q?(b.each(q,function(c,d){b.each(c,function(b){var c=b.extension;a.addErrorClass(b.$field);c&&(b="#auth-"+d+c,c=p(b+w),c.length?c.show():p(b).show())})}),p("#message-box-slot").hide(),d.show(),c.find(".a-form-error").first().focus()):d.hide()}function t(a){return"string"!==typeof a||0===a.length?"":Array.prototype.map.call(a,function(a){var b=a.charCodeAt(0);return 65280<=
b&&65519>=b?String.fromCharCode(b-65248):12288===b?String.fromCharCode(32):a}).join("")}function B(a){a.find("input[name=email], input[name=customerName], input[name=customerNamePronunciation], input[name=emailLogin], input[name=guess]").each(function(){if(""!==p(this).val()){var a=t(p(this).val());p(this).val()!==a&&(p(this).val(a),c.incrementCounter(c.getCounterNameWithDeviceAndPageType("SingleClaimFieldFullWidthRemoval")))}})}var p=b.$,y=/Check$/g,w="",q;return{validate:function(b){b=b&&b.jquery?
b:p(b);if(b.length&&b.is("form")){w=b.hasClass("ap_ango_phone")?"-ango-phone":b.hasClass("ap_ango_email")?"-ango-email":"";B(b);n(b);l(b);f(b);g(b);u(b);h(b);q&&c.incrementCounter(e.getFormName(b)+"PreventedServerRoundTrips"+a.determineDeviceType());r(b);var d=!q;b.data("auth-validation-errors",q);q=void 0;return d}},getErrors:function(a){return(a.jquery?a:p(a)).data("auth-validation-errors")}}});f.when("A","auth-validate-form-handler","ready").register("auth-validate-form-moa",function(b,
a){var c=b.$;c(document.body).delegate(".auth-validate-form-moa","submit",function(b){a.validate(this)||b.preventDefault()})});f.when("A","auth-validate-form-handler","auth-validate-form-common","client-side-counters-util","page-util","AuthToolkit","ready").register("auth-validate-form",function(b,a,c,e,d,h){var f=b.$;f(document.body).delegate(".auth-validate-form","submit",function(b){e.incrementCounter(d.getFormName(this)+"Submit"+c.determineDeviceType());if(!a.validate(this)){var g=f(this).find("span.auth-disable-button-on-submit.a-button-disabled");
typeof g!==n&&0<g.length&&h.enableButton(g);b.preventDefault()}})});f.when("A","auth-validate-form-common","ready").register("auth-validate-form-real-time",function(b,a){function c(b,c,d){a.isErrorVisible(b,c)&&d(b)&&a.hideErrorMessage(b,a.getErrorAlertExtension(c))}function e(b,c){if(b.hasClass("auth-require-fields-match")){var d=b.closest(".auth-require-fields-match-group");if(d!==h&&(d=d.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-fields-match")),2===d.length)){var e=
d.eq(0),f=d.eq(1);a.isErrorVisible(e,"auth-require-fields-match")&&c(d)&&(a.hideErrorMessage(e,a.getErrorAlertExtension("auth-require-fields-match")),a.removeErrorClass(f))}}}var d=b.$,h;d(".auth-real-time-validation input").bind("keyup.clearValidationErrors",function(){var b=d(this);c(b,"auth-required-field",a.isNonEmptyField);c(b,"auth-require-email-validaton",a.isValidEmailField);c(b,"auth-require-phone-validation",a.isValidPhoneNumberField);c(b,"auth-require-claim-validation",a.isValidClaimField);
c(b,"auth-require-password-validation",a.isValidPasswordField);e(b,a.isMatchingFields)});return{clearErrorMessageOnMatchingInputs:e}});f.when("A","AuthToolkit","ready").register("auth-3p-phone-verification",function(b,a){function c(){l.NativeUI&&"function"===typeof l.NativeUI.applyFullFlash&&l.setTimeout(function(){l.NativeUI.applyFullFlash()},900)}var e=b.$,d=e("#auth-pv-enter-code");a.countingDown("#ap-3p-get-pin-code-button");b.on("AuthToolkit.countDownEnd",function(a){"#ap-3p-get-pin-code-button"===
a&&(e("#auth-phone-number").removeClass("a-form-disabled"),e("#auth-phone-number-wrapper").removeClass("a-form-disabled"),e("#auth-phone-number").attr("disabled",!1))});b.on("a:dropdown:auth-country-picker:select",c);d.bind("change paste keyup",function(){0<e(this).val().length?a.enableButton("#ap-3p-pv-create-account"):a.disableButton("#ap-3p-pv-create-account")});e("#auth-verify-button").click(function(){var a=e("#auth-3p-pv-form");a.find("#insisted").val("false");a.find("#getPinCodeAction").val("true");
a.submit()});e("#ap-3p-insist-verify-link").click(function(){var a=e("#auth-3p-pv-form");a.find("#auth-country-picker").val(e("#ap-3p-insist-verify-link").attr("countrycode"));a.find("#auth-phone-number").val(e("#ap-3p-insist-verify-link").attr("phonenumber"));a.find("#insisted").val("true");a.submit()});return{callApplyFullFlash:c}});f.when("A","a-modal","ready").register("ap-3p-pv-modal",function(b,a){var c=b.$,e=b.state("ap-3p-pv-modal");if(e){var d=e.thirdPartyPhoneConflict;if(d&&"None"!==d.toString()){var h=
c("#"+e.formIdToBindTo),c=c("#ap-3p-pv-modal-action");(c=a.get(c))&&d&&"None"!==d.toString()&&c.show();b.declarative("ap-3p-pv-modal-complete","click",function(){d&&"WeChat"===d.toString()&&(h.find("#insisted").val("true"),h.submit())})}}});f.when("A","a-modal","ready").register("ap-3p-account-connected-modal",function(b,a){var c=b.$,e=b.state("ap-3p-account-connected-modal");e&&e.thirdPartyAccountStatus&&"rejectWithLoginIdIfConnected"===e.thirdPartyAccountStatus&&(c=c("#ap-3p-account-connected-modal-action"),
(c=a.get(c))&&c.show())});f.when("A").execute(function(b){function a(a){var c=b.state("moa_registration_v2_info");c&&c.enabled&&b.get("/ap/nocontent/ref="+a+"_"+c.device,{})}var c=b.$;c("#ap_use_email").click(function(){a("ap_mmoar_usee")});c("#ap_use_mobile").click(function(){a("ap_mmoar_usem")});c("#auth-country-picker-container").click(function(){a("ap_mmoar_ccp")});c("#continue").click(function(){a("ap_mmoar_cont")});b.on("a:popover:show:verifyContinueModal",function(){a("ap_mmoar_vm_o")});
b.on("a:popover:hide:verifyContinueModal",function(){a("ap_mmoar_vm_c")});c("#auth-verification-ok-announce").click(function(){a("ap_mmoar_vm_ok")});c("#auth-already-have-account").click(function(){a("ap_mmoar_signin")});c("#auth-verify-button").click(function(){a("ap_mmoar_pv_verify")});c("#auth-resend-code-link").click(function(){a("ap_mmoar_pv_resend")})});f.when("A","jQuery","ready").register("wechat-wxlogin-js",function(b,a){if(0<a("#auth-wechat-login-container").length){var c=a("#auth-wechat-login-container").data("wechatUrl");
f.load.js(c)}});f.when("A","jQuery","client-side-counters-util","wechat-login-button-counter","wechat-wxlogin-js","ready").register("wechat-qrcode-module",function(b,a,c,e){if(0<a("#auth-wechat-login-container").length){var d=function(){var b=a("div#auth-interactive-dialog-content"),c=a("div#auth-wechat-qrcode-loading-container").clone();c.removeClass("hidden");c.appendTo(b);a("div#auth-interactive-dialog").css("display","table");var d=a("#auth-wechat-login-container"),b=d.data("appid"),c=d.data("scope"),
e=d.data("redirectUrl"),h=d.data("state"),d=d.data("style");new l.WxLogin({id:"auth-wechat-qrcode-container",appid:b,scope:c,redirect_uri:e,state:h,style:d})},h=function(){var b=a("div#auth-interactive-dialog-content");a("div#auth-interactive-dialog").css("display","none");b.empty()};a("div#auth-interactive-dialog-content").click(function(a){a.stopImmediatePropagation()});a("#auth-wechat-login-container").click(function(){c.incrementCounter(e.weChatButtonClickEventCounterName);d()});a("div#auth-interactive-dialog-container").click(function(){h()});
return{showWeChatQRCode:d,hideWeChatQRCode:h}}});f.when("A","client-side-counters-util","counters-name","ready").register("wechat-login-button-counter",function(b,a,c){var e=c.getCommonCounterNamePrefix()+":WeChat";c=b.$("#auth-wechat-login-container-noninteractive");0<c.length&&c.click(function(){a.incrementCounter(e)});b=b.$("a#signInSubmit.wechat_button");0<b.length&&b.click(function(){a.incrementCounter(e)});return{weChatButtonClickEventCounterName:e}});f.when("A").register("wechat",
function(b){function a(a,b){return c.ajax({url:"https://res.wx.qq.com/connect/zh_CN/htmledition/js/wxLogin.js",dataType:"script",success:a,error:b,cache:!0})}var c=b.$,e=!1,d=null;return{WxLogin:function(b,f){f&&c.isFunction(f)||(f=function(){});e?f(new d(b)):a(function(){e=!0;d=l.WxLogin;f(new d(b));c("#identity-provider-pagelet-wechat-gray-block").fadeOut()},function(){f()})}}});f.when("A","wechat","ready").execute(function(b,a){var c=b.$,c=c("#auth-identity-provider-wechat-qrcode-container");0!==
c.length&&(a.WxLogin({id:"auth-identity-provider-wechat-qrcode-container",appid:c.data("appid"),scope:c.data("scope"),redirect_uri:c.data("redirect-uri"),state:c.data("state"),style:c.data("style")}),setTimeout(function(){l.location.reload()},9E5))});f.when("A","auth-form-field-utils","cvf","client-side-counters-util","ready").register("auth-contact-verification-handler",function(b,a,c,e){function d(d){var g=this;d=d||{};this.postVerificationSuccessCallback=d.postVerificationSuccessCallback||
k.noop;this.$verificationForm=k("form.auth-contact-verification-form");this.$contactVerificationWidgetTarget=k(".auth-contact-verification-widget-target").first();this.$claimToken=this.$verificationForm.find('input[type="hidden"].auth-contact-verification-claim-token');this.$verifyContactButton=this.$verificationForm.find(".auth-contact-verification-button");this.contactVerificationEndpoint=this.$verificationForm.attr("action");this.postVerificationFormAction=this.$verificationForm.data("post-verification-action");
this.$verificationTarget=this.$verificationForm.find(".auth-contact-verification-target");this.$spinnerTarget=this.$verificationForm.find(".auth-contact-verification-spinner");this.$successMessage=this.$verificationForm.find(".auth-contact-verification-success-message");this.preVerify="preVerify";this.pendingVerify="pendingVerify";this.verifyState=g.preVerify;this.formSubmitEvent="submit.contactVerification";this.$reverifyOnChangeTarget=k(".auth-require-reverify-on-change, .auth-require-reverify-on-change :input");
this.verificationFlowCompleteTime=this.verifyRequestCompleteTime=this.verificationFlowStartTime=0;this.disableTargetLabelCssClass="a-color-tertiary";this.errorCodes="&errorCodes=";this.internalError="INTERNAL_ERROR";this.ajax=function(a,c){b.ajax(a,c)};this.startContactVerification=function(){g.verificationFlowStartTime=(new Date).getTime();g.ajax(g.contactVerificationEndpoint,{method:"post",cache:!1,params:h(g.$verificationForm),error:g.startContactVerificationError,success:g.initializeComposableVerificationWidget})};
this.startContactVerificationError=function(a,b,c){f.log("Error contacting contact verification endpoint: "+c+". Customers will not be able to verify their contact information.","INFO");e.incrementCounter("contactVerificationAjaxFailureContactVerificationInit");l.location.href=l.location.href+g.errorCodes+g.internalError};this.cvfWidgetFactory=c;this.initializeComposableVerificationWidget=function(a){a=a||{};a.location?l.location.href=a.location:(a=a.requestToken||"",g.verifyRequestCompleteTime=(new Date).getTime(),
a={target:g.$contactVerificationWidgetTarget,requestToken:a,onSuccess:g.completeContactVerification,onError:g.widgetInitializationError,autoStart:!1},g.$spinnerTarget&&(a.spinnerTarget=g.$spinnerTarget),g.cvfWidgetFactory.create(a).start())};this.widgetInitializationError=function(a,b,c){f.log("Error initializing verification widget: "+c+". Customers will not be able to verify their contact information.","INFO");e.incrementCounter("contactVerificationAjaxFailureWidgetInit");l.location.href=l.location.href+
g.errorCodes+g.internalError};this.setClaimToken=function(a){g.$claimToken.val(a)};this.completeContactVerification=function(b,c){g.verificationFlowCompleteTime=(new Date).getTime();c?(g.setClaimToken(b),g.setPostVerificationAction(),g.$successMessage.show(),g.$verificationForm.unbind(g.formSubmitEvent),g.$verificationTarget.each(function(){a.enableInput(k(this));var b=k("label[for='"+k(this).attr("id")+"']");b.length&&b.removeClass(g.disableTargetLabelCssClass)}),e.insertCounter("contactVerificationCompleteVerificationFlowCompleteTime",
g.verificationFlowCompleteTime-g.verificationFlowStartTime),e.insertCounter("contactVerificationVerifyRequestCompleteTime",g.verifyRequestCompleteTime-g.verificationFlowStartTime),k.isFunction(g.postVerificationSuccessCallback)&&g.postVerificationSuccessCallback()):l.location.href=l.location.href+g.errorCodes+g.internalError};this.setPostVerificationAction=function(){g.$verificationForm.prop("action",g.postVerificationFormAction)};this.verificationRequestHandler=function(a){a.preventDefault();g.$spinnerTarget&&
g.$spinnerTarget.show();g.verifyState=g.pendingVerify;g.$verifyContactButton.hide();g.startContactVerification()};this.bindVerificationFormEvent=function(){g.$verificationForm.bind(g.formSubmitEvent,g.verificationRequestHandler)};g.bindVerificationFormEvent();this.unbindVerificationFormEvent=function(){g.$verificationForm.unbind(g.formSubmitEvent)};this.safeBind=function(){g.unbindVerificationFormEvent();g.bindVerificationFormEvent()};this.resetContactVerificationOnRequestInfoChange=function(){g.$reverifyOnChangeTarget.bind("keyup",
function(a){a.preventDefault();a=13===a.keyCode;g.verifyState===g.preVerify||a||(b.trigger("cvf:claim:changed"),g.verifyState=g.preVerify,g.reVerifyEmail());g.$claimToken.val()&&g.safeBind()})};g.resetContactVerificationOnRequestInfoChange();this.reVerifyEmail=function(){g.$contactVerificationWidgetTarget.empty();g.$verifyContactButton.show();g.$successMessage.hide();g.disableVerificationTarget();g.$verificationForm.prop("action",g.contactVerificationEndpoint)};this.disableVerificationTarget=function(){g.$verificationTarget.each(function(){a.disableInput(k(this));
var b=k("label[for='"+k(this).attr("id")+"']");b.length&&b.addClass(g.disableTargetLabelCssClass)})}}function h(b){b=b.find("input.auth-contact-verification-request-info, input[type=hidden]");return a.inputsToJson(b)}var k=b.$;return{create:function(a){e.incrementCounter("contactVerificationCVFCreate");return new d(a)},ContactVerificationHandler:d}});f.when("auth-contact-verification-handler","ready").register("auth-contact-verification-autostart",function(b){return b.create()});
f.when("A").register("auth-form-field-utils",function(b){function a(a){a.prop("disabled",!1);a.removeClass("a-form-disabled");a.find("input").prop("disabled",!1)}function c(a){a.removeClass("a-button-disabled");a.find("input").prop("disabled",!1)}function e(a){a.prop("disabled",!0);a.addClass("a-form-disabled");a.find("input").prop("disabled",!0)}function d(a){a.addClass("a-button-disabled");a.find("input").prop("disabled",!0)}var h=b.$;return{enableTextInput:a,enableButton:c,enableInput:function(b){0<
b.closest(".a-button").length?c(b):(b.hasClass("a-input-text")||b.hasClass("a-input-text-wrapper"))&&a(b)},disableTextInput:e,disableButton:d,disableInput:function(a){0<a.closest(".a-button").length?d(a):(a.hasClass("a-input-text")||a.hasClass("a-input-text-wrapper"))&&e(a)},inputsToJson:function(a){return a.map(function(){var a=h(this);if(a.is("input")){var b={};b[a.attr("name")]=a.val();return b}}).toArray().reduce(function(a,b){return h.extend(a,b)})}}});f.when("page-util").register("client-side-counters-util",
function(b){function a(a,b){var d=l.ue;d&&"function"===typeof d.count&&(b||(b=(d.count(a)||0)+1),d.count(a,b))}return{incrementCounter:function(b){a(b)},insertCounter:a,getCounterNameWithDeviceAndPageType:function(a){return a+b.determineDeviceType()+b.determinePageType()}}});f.when("A","AuthToolkit","auth-pv-resend-utility","ready").register("auth-cnep-add-password",function(b,a,c){var e=b.$;if(!(1>e("#ap-cnep-add-password-resend-code-button").length)){a.countingDown("#ap-cnep-add-password-resend-code-button");
var d=b.state("auth-cnep-add-password-resend-state");if(d){var h=e("#auth-cnep-add-password-client-side-success-box"),f=e(".auth-pv-client-side-success-messages li"),l=e("#auth-cnep-add-password-client-side-error-box"),g=e(".auth-pv-client-side-error-messages li"),n=e(".auth-server-side-message-box"),D=e("#auth-resend-code-succeeded"),v=e("#auth-there-was-an-error-throttled"),r=e("#auth-there-was-an-error");d.sessionTimeoutUrl=d.cnepUrl;var t=function(){c.successHandler(D,h)},B=function(a){c.errorHandler(a,
d,v,r,l)};e("#ap-cnep-add-password-resend-code-button").click(function(){"#ap-cnep-add-password-resend-code-button".isDisabled||(c.hideMessageBox(h,f,l,g,n),b.ajax(d.resendPinCodeUrl,{method:"post",success:t,error:B}),"undefined"===typeof e("#ap-cnep-add-password-resend-code-button")||e("#ap-cnep-add-password-resend-code-button").hasClass("a-button-disabled")||(e("#ap-cnep-add-password-resend-code-button").addClass("a-button-disabled"),e("#ap-cnep-add-password-resend-code-button").find(".a-button-text").attr("disabled",
"disabled")),e("#ap-cnep-add-password-resend-code-button").find(".a-button-text").data("remaining",d.originalRemaining),a.countingDown("#ap-cnep-add-password-resend-code-button"))})}}});f.when("A","ready").register("counters-name",function(b){return{getCommonCounterNamePrefix:function(){var a="unknown",c=l.location.pathname.split("/");0<c.length&&(a=c[c.length-1]);var c="",e=b.state("auth-csm-page-state");e&&(c=e.assocHandle);return["AuthenticationPortal",a,c].join(":")}}});
f.when("A").register("page-util",function(b){function a(a){a.jquery||d(a);return c(d("form:visible").attr("name"))}function c(a){if(a)return a.replace(/(?:-| |\b)(\w)/g,function(a,b){return b.toUpperCase()})}function e(){return d("html").hasClass("a-mobile")}var d=b.$;return{getFormName:a,toCamelCase:c,determinePageType:function(){for(var b={SignIn:"SignInPage",Register:"RegistrationPage",ForgotPassword:"Fpp"},c=document.getElementsByTagName("form"),d=0;d<c.length;d++){var e=a(c[d]);if(e in b)return b[e]}},
determineDeviceType:function(){return e()?"OnMobile":"OnDesktop"},isMobile:e}});f.when("A","client-side-counters-util","page-util").register("passwordless-auth",function(b,a,c){var e=b.$,d=b.state("login-with-otp-state"),h=e("#ap_login_form #continue");l.loginWithOTPState=d!==n?d.isLoginWithOTPEnabled:!1;e("#auth-skip-reset-password-link").click(function(){b.get("/ap/nocontent/ref=ap_fpp_skip_on_reset_pwd",{});a.incrementCounter("SkipResetPasswordOnResetPage"+c.determineDeviceType())});
b.on("credentialsEntered",function(){!0===l.loginWithOTPState&&(a.incrementCounter("SharedWebCredentialsSubmitted"),h.click())})});f.when("A","client-side-counters-util","a-checkbox","ready").register("auth-remember-me",function(b,a,c){function e(b){b.val()!==f?(c(l).isChecked()&&a.incrementCounter(a.getCounterNameWithDeviceAndPageType("UncheckRMCheckboxForUnrecognizedEmail")),c(l).uncheck()):""!==b.val()&&(c(l).check(),a.incrementCounter(a.getCounterNameWithDeviceAndPageType("BackToCheckedRMCheckboxForRecognizedEmail")))}
b=b.$;var d=b("#ap_email, #ap-credential-autofill-hint"),h=b("#ap_email_icon"),f=d.val(),l=b("input[name=rememberMe]");d.bind("keyup.uncheckRememberMe",function(){""!==f&&e(d)});h.click(function(){e(d)})});f.when("A","client-side-counters-util","page-util","ready").register("auth-remove-mobile-claim",function(b,a,c){b=b.$;var e=b("#auth-remove-phone-claim");b("#ap-remove-mobile-claim-submit-button").click(function(){e.submit();a.incrementCounter("RemoveMobileClaimSubmitAttempt"+c.determineDeviceType())})});
f.when("A","client-side-counters-util","ready").execute(function(b,a){b.on("a:expander:blacklist_password_learn_more:toggle:expand",function(b){a.incrementCounter("BlacklistPasswordInstructionLearnMoreExpand")});b.on("a:expander:blacklist_password_learn_more:toggle:collapse",function(b){a.incrementCounter("BlacklistPasswordInstructionLearnMoreCollapse")})});f.when("A","ready").register("auth-footer-language-picker",function(b){b.on("a:dropdown:selected:languagePicker",function(a){l.location.href=
a.value})});f.when("A").execute(function(b){b.declarative("other-languge-option-click","click",function(a){"input"===a.targetTag&&(l.location.href=a.$target[0].value)})});f.when("A","ready").register("account_conflict_continue_verify",function(b){var a=b.$;a("#auth-account-conflict-continue-verify-url").click(function(b){b.preventDefault();b=a("#ap_account_conflict_warning_customer_actions");b.exists()&&b.submit()});a.fn.exists=function(){return 0!==this.length}});f.when("A").register("handle-ios-redirect",
function(b){document.getElementById("returnToUrl")&&0!==document.getElementById("returnToUrl").getElementsByTagName("a").length&&(l.location.href=document.getElementById("returnToUrl").getElementsByTagName("a")[0].href)});f.when("A","auth-validate-form-common","client-side-counters-util").register("moa-single-claim-input-common",function(b,a,c){function e(b){return a.isNonBlankField(b)?a.isValidPhoneNumberField(b)?f.PHONE:f.EMAIL:f.UNKNOWN}var d=b.$,f={PHONE:"PHONE",EMAIL:"EMAIL",UNKNOWN:"UNKNOWN"};
Object.freeze(f);var k={};k[f.PHONE]="phone-text";k[f.EMAIL]="email-text";k[f.UNKNOWN]="default-text";Object.freeze(k);var l={};l[f.PHONE]="SingleClaimFieldPhone";l[f.EMAIL]="SingleClaimFieldEmail";Object.freeze(l);var g={REGISTER:"registerPage",SIGNIN:"signInPage"};Object.freeze(g);d.fn.auiShow=function(){d(this).removeClass("a-hidden aok-hidden").show();return this};d.fn.auiHide=function(){d(this).addClass("aok-hidden").hide();return this};return{showPasswordInformationMessage:function(a){a=a&&
a.$currentTarget||d(a.target);a.closest(".a-row").parent().find(".auth-inlined-error-message").is(":visible")||a.closest(".a-row").parent().find("#passwordInformationMessage").auiShow()},hidePasswordInformationMessage:function(a){var c=a&&a.$currentTarget||d(a.target);c.closest(".a-row").parent().find("#passwordInformationMessage").auiHide();a.$event&&a.$event.relatedTarget&&"submit"===a.$event.relatedTarget.type&&b.delay(function(){c.closest("form").submit()})},incrementCounterForSelectedClaim:function(a){a=
e(a);c.incrementCounter(c.getCounterNameWithDeviceAndPageType(l[a]))},incrementCounterForPlusSymbolAtStartOfClaim:function(){c.incrementCounter(c.getCounterNameWithDeviceAndPageType("PlusSymbolAtStartOfClaim"))},incrementCounterForToggleCountryPicker:function(a){c.incrementCounter(c.getCounterNameWithDeviceAndPageType(a?"CountryPickerEnabled":"CountryPickerDisabled"))},getClaimType:e,ClaimType:f,PageType:g,ButtonTextToClass:k,isValidEmail:/^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,
invalidPhoneRegex:/^ *\+|[a-zA-Z]|@/}});f.when("A","moa-single-claim-input-field_handler","ready").register("moa-single-claim-input-field",function(b,a){var c=b.$;c("#ap_email");b.declarative("single_claim_handler","focusout keyup",a.inputHandler);b.declarative("single_claim_password_handler","focusout focusin keyup",a.passwordHandler);b.declarative("show-countries","click",a.showCountries);b.on("a:dropdown:auth-country-picker:select",a.updateCountryDisplayText)});f.when("A",
"auth-validate-form-common","client-side-counters-util","moa-single-claim-input-common","a-dropdown").register("moa-single-claim-input-field_handler",function(b,a,c,e,d){function f(a){D("#auth-continue .a-button-text span").auiHide();D("#auth-continue ."+a).auiShow()}function k(a){var b=a.closest(".a-section").find(".country-picker");b&&n(a)?(b=b.outerWidth(),a.css({"padding-left":b+"px"})):a.css({"padding-left":""})}function l(a,b){var c=a.closest(".moa-single-claim-container").find("select").attr("id");
d.getSelect(c).update({status:b})}function g(a){n(a)||(l(a,"enabled"),a.closest(".a-section").find(".country-picker").auiShow(),k(a),e.incrementCounterForToggleCountryPicker(!0))}function n(a){return a.closest(".a-section").find(".country-picker").is(":visible")}var D=b.$;return{inputHandler:function(b){if("focusout"===b.type){var c=b.$currentTarget.find("input");if(!(0>=c.size()))switch(e.getClaimType(c)){case e.ClaimType.PHONE:f(e.ButtonTextToClass.PHONE);break;case e.ClaimType.EMAIL:f(e.ButtonTextToClass.EMAIL);
break;default:f(e.ButtonTextToClass.UNKNOWN)}}if("focusout"===b.type||"keyup"===b.type){var c=b.$target,d=c.val()&&c.val().trim()||"";b=b.$event.which;16<=b&&46>b||(1===d.length&&"+"===d.charAt(0)||"+"===d.charAt(0)&&a.isValidPhoneWithCountryCodeSelector(d.substr(1))?(c.val(c.val().substr(1)),g(c),e.incrementCounterForPlusSymbolAtStartOfClaim()):d&&a.isValidPhoneWithCountryCodeSelector(d)?g(c):n(c)&&(l(c,"disabled"),c.closest(".a-section").find(".country-picker").auiHide(),k(c),e.incrementCounterForToggleCountryPicker(!1)))}},
passwordHandler:function(a){"keyup"===a.type||"focusin"===a.type?e.showPasswordInformationMessage(a):"focusout"===a.type&&e.hidePasswordInformationMessage(a)},showCountries:function(a){a.$currentTarget.closest(".moa-single-claim-container").find(".moa-country-picker-select-container .a-declarative").click()},updateCountryDisplayText:function(a){var b=D(a.selectNode),c=b.closest(".moa-single-claim-container").find(".country-picker"),b=b.closest(".moa-single-claim-container").find("input[name=email]");
a=a.nativeItemNode.text;c.find(".a-declarative").text(a);k(b)}}});f.when("A","AuthToolkit","client-side-counters-util","ready").register("disable-button",function(b,a,c){var e=b.$,d=e("span.auth-disable-button-on-submit");typeof d!==n&&0<d.length&&d.closest("form").bind("submit",function(){a.disableButton(d);b.delay(function(){c.incrementCounter("NoPostbackFromSubmit");a.enableButton(d)},4E3)})});f.when("A","ready").execute("password-encryption-setup",function(b){var a=b.state("sif-encryption-profile");
a&&f.when("auth-validate-form-handler","siege-cse:profile:"+a.sifProfile).execute("password-encryption",function(c,e){function d(c){function d(a){b.$(c).unbind(".encryption").submit()}try{var f=e.createFormHandler(c);f.configure({formProfile:a.sifProfile,encryptionContext:{}});var g=b.$(c).find("input[name='password']").val().length;f.generateProcessedForm({}).then(function(a){var c=b.$(a).find("input[name='password']").val().length;if(g===c)c=document.createElement("INPUT"),c.setAttribute("type",
"hidden"),c.setAttribute("name","passwordNotEncrypted"),a.appendChild(c);else{var d=document.createElement("INPUT");d.setAttribute("type","hidden");d.setAttribute("name","encryptedPasswordLength");d.setAttribute("value",c);a.appendChild(d)}c=document.createElement("INPUT");c.setAttribute("type","hidden");c.setAttribute("name","passwordEncrypted");a.appendChild(c);a.submit()}).catch(d)}catch(l){d(l)}}b.$("input[name='password']").closest("form").not("#ap_register_form").bind("submit.encryption",function(a){a.preventDefault();
c.validate(this)&&d(this)})})})});
/* ******** */
